### Converting bracken output to normalized ASV table

#### let's start with species level

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import os

In [4]:
os.chdir('/work/pi_sarah_gignouxwolfsohn_uml_edu/nikea/COL/ID_tables')

In [5]:
os.chdir('/scratch4/workspace/nikea_ulrich_uml_edu-col_data/kraken2_pluspf/bracken_ready')

In [6]:
# Set path variables and create sample list 
SAMPLES='/work/pi_sarah_gignouxwolfsohn_uml_edu/nikea/COL/ID_tables/all_sampleids.txt'
BRACKENS='/scratch4/workspace/nikea_ulrich_uml_edu-col_data/kraken2_pluspf/bracken_ready/species'
samplelist=[]

with open(SAMPLES) as samples:
    for line in samples:
        samplelist.append(line.strip())
print(samplelist)

sample_names_string = ','.join(samplelist)
print(sample_names_string)
print(len(samplelist))

['032024_COL_SAN_T5_139_OFAV_S17', '032024_COL_SAN_T5_140_OFAV_S18c', '032024_COL_SAN_T5_141_OFAV_S19', '032024_COL_SAN_T5_166_OFAV_S20', '032024_COL_SAN_T5_167_OFAV_S21', '012025_COL_SAN_T5_568_OFAV_S1', '012025_COL_SAN_T5_572_OFAV_S5', '012025_COL_SAN_T5_580_OFAV_S13', '012025_COL_SAN_T5_584_OFAV_S17', '012025_COL_SAN_T5_585_OFAV_S18', '012025_COL_SAN_T5_596_OFAV_S29', '032024_COL_SAN_T5_128_MCAV_S1', '032024_COL_SAN_T5_129_MCAV_S2', '032024_COL_SAN_T5_130_MCAV_S37', '032024_COL_SAN_T5_131_MCAV_S3', '032024_COL_SAN_T5_132_MCAV_S4', '032024_COL_SAN_T5_133_MCAV_S5', '032024_COL_SAN_T5_134_MCAV_S6', '032024_COL_SAN_T5_136_MCAV_S7', '032024_COL_SAN_T5_150_MCAV_S8', '012025_COL_SAN_T5_574_MCAV_S7', '012025_COL_SAN_T5_578_MCAV_S11', '012025_COL_SAN_T5_581_MCAV_S14', '012025_COL_SAN_T5_583_MCAV_S16', '012025_COL_SAN_T5_588_MCAV_S21', '012025_COL_SAN_T5_589_MCAV_S22', '012025_COL_SAN_T5_591_MCAV_S24', '012025_COL_SAN_T5_593_MCAV_S26', '012025_COL_SAN_T5_594_MCAV_S27', '012025_COL_SAN_T5_595_MCAV_S28', '032024_COL_SAN_T5_146_DLAB_S12', '032024_COL_SAN_T5_148_DLAB_S13', '032024_COL_SAN_T5_149_DLAB_S14', '032024_COL_SAN_T5_158_DLAB_S15', '032024_COL_SAN_T5_159_DLAB_S16', '032024_COL_SAN_T5_143_DLAB_S40', '032024_COL_SAN_T5_160_DLAB_S41', '032024_COL_SAN_T5_161_DLAB_S42', '012025_COL_SAN_T5_569_DLAB_S2', '012025_COL_SAN_T5_570_DLAB_S3', '012025_COL_SAN_T5_571_DLAB_S4', '012025_COL_SAN_T5_575_DLAB_S8', '012025_COL_SAN_T5_579_DLAB_S12', '012025_COL_SAN_T5_586_DLAB_S19', '032024_COL_SAN_T5_144_PSTR_S9', '032024_COL_SAN_T5_147_PSTR_S10', '032024_COL_SAN_T5_163_PSTR_S11c', '032024_COL_SAN_T5_154_PSTR_S38', '032024_COL_SAN_T5_162_PSTR_S39', '012025_COL_SAN_T5_573_PSTR_S6', '012025_COL_SAN_T5_576_PSTR_S9', '012025_COL_SAN_T5_577_PSTR_S10', '012025_COL_SAN_T5_582_PSTR_S15', '012025_COL_SAN_T5_587_PSTR_S20', '012025_COL_SAN_T5_590_PSTR_S23', '012025_COL_SAN_T5_592_PSTR_S25']
032024_COL_SAN_T5_139_OFAV_S17,032024_COL_SAN_T5_140_OFAV_S18c,032024_COL_SAN_T5_141_OFAV_S19,032024_COL_SAN_T5_166_OFAV_S20,032024_COL_SAN_T5_167_OFAV_S21,012025_COL_SAN_T5_568_OFAV_S1,012025_COL_SAN_T5_572_OFAV_S5,012025_COL_SAN_T5_580_OFAV_S13,012025_COL_SAN_T5_584_OFAV_S17,012025_COL_SAN_T5_585_OFAV_S18,012025_COL_SAN_T5_596_OFAV_S29,032024_COL_SAN_T5_128_MCAV_S1,032024_COL_SAN_T5_129_MCAV_S2,032024_COL_SAN_T5_130_MCAV_S37,032024_COL_SAN_T5_131_MCAV_S3,032024_COL_SAN_T5_132_MCAV_S4,032024_COL_SAN_T5_133_MCAV_S5,032024_COL_SAN_T5_134_MCAV_S6,032024_COL_SAN_T5_136_MCAV_S7,032024_COL_SAN_T5_150_MCAV_S8,012025_COL_SAN_T5_574_MCAV_S7,012025_COL_SAN_T5_578_MCAV_S11,012025_COL_SAN_T5_581_MCAV_S14,012025_COL_SAN_T5_583_MCAV_S16,012025_COL_SAN_T5_588_MCAV_S21,012025_COL_SAN_T5_589_MCAV_S22,012025_COL_SAN_T5_591_MCAV_S24,012025_COL_SAN_T5_593_MCAV_S26,012025_COL_SAN_T5_594_MCAV_S27,012025_COL_SAN_T5_595_MCAV_S28,032024_COL_SAN_T5_146_DLAB_S12,032024_COL_SAN_T5_148_DLAB_S13,032024_COL_SAN_T5_149_DLAB_S14,032024_COL_SAN_T5_158_DLAB_S15,032024_COL_SAN_T5_159_DLAB_S16,032024_COL_SAN_T5_143_DLAB_S40,032024_COL_SAN_T5_160_DLAB_S41,032024_COL_SAN_T5_161_DLAB_S42,012025_COL_SAN_T5_569_DLAB_S2,012025_COL_SAN_T5_570_DLAB_S3,012025_COL_SAN_T5_571_DLAB_S4,012025_COL_SAN_T5_575_DLAB_S8,012025_COL_SAN_T5_579_DLAB_S12,012025_COL_SAN_T5_586_DLAB_S19,032024_COL_SAN_T5_144_PSTR_S9,032024_COL_SAN_T5_147_PSTR_S10,032024_COL_SAN_T5_163_PSTR_S11c,032024_COL_SAN_T5_154_PSTR_S38,032024_COL_SAN_T5_162_PSTR_S39,012025_COL_SAN_T5_573_PSTR_S6,012025_COL_SAN_T5_576_PSTR_S9,012025_COL_SAN_T5_577_PSTR_S10,012025_COL_SAN_T5_582_PSTR_S15,012025_COL_SAN_T5_587_PSTR_S20,012025_COL_SAN_T5_590_PSTR_S23,012025_COL_SAN_T5_592_PSTR_S25
56

In [7]:
otu_table=pd.read_csv("/scratch4/workspace/nikea_ulrich_uml_edu-col_data/kraken2_pluspf/bracken_ready/all_merged_bracken_S.txt", sep='\t')

In [8]:
otu_table.set_index("taxonomy_id",inplace=True)

In [9]:
otu_table.head()

,name,taxonomy_lvl,012025_COL_SAN_T5_568_OFAV_S1_S_filt.bracken_num,012025_COL_SAN_T5_568_OFAV_S1_S_filt.bracken_frac,012025_COL_SAN_T5_569_DLAB_S2_S_filt.bracken_num,012025_COL_SAN_T5_569_DLAB_S2_S_filt.bracken_frac,012025_COL_SAN_T5_570_DLAB_S3_S_filt.bracken_num,012025_COL_SAN_T5_570_DLAB_S3_S_filt.bracken_frac,012025_COL_SAN_T5_571_DLAB_S4_S_filt.bracken_num,012025_COL_SAN_T5_571_DLAB_S4_S_filt.bracken_frac,...,032024_COL_SAN_T5_161_DLAB_S42_S_filt.bracken_num,032024_COL_SAN_T5_161_DLAB_S42_S_filt.bracken_frac,032024_COL_SAN_T5_162_PSTR_S39_S_filt.bracken_num,032024_COL_SAN_T5_162_PSTR_S39_S_filt.bracken_frac,032024_COL_SAN_T5_163_PSTR_S11c_S_filt.bracken_num,032024_COL_SAN_T5_163_PSTR_S11c_S_filt.bracken_frac,032024_COL_SAN_T5_166_OFAV_S20_S_filt.bracken_num,032024_COL_SAN_T5_166_OFAV_S20_S_filt.bracken_frac,032024_COL_SAN_T5_167_OFAV_S21_S_filt.bracken_num,032024_COL_SAN_T5_167_OFAV_S21_S_filt.bracken_frac
taxonomy_id,,,,,,,,,,,,,,,,,,,,,
28213,Sphingomonas parapaucimobilis,S,4188,0.02768,40,0.00025,211,0.00070,192,0.00070,...,145,0.00018,0,0.00000,3501,0.00783,0,0.00000,0,0.00000
562,Escherichia coli,S,3624,0.02396,1019,0.00646,11006,0.03627,23466,0.08545,...,13546,0.01649,1884,0.00380,2260,0.00506,1923,0.02684,1407,0.02580
2961995,Marinobacter metalliresistant,S,2234,0.01477,0,0.00000,55,0.00018,0,0.00000,...,0,0.00000,0,0.00000,0,0.00000,1830,0.02554,958,0.01756
2721244,Streptomyces sp. RPA4-2,S,1909,0.01262,419,0.00266,129,0.00043,411,0.00150,...,295,0.00036,324,0.00065,372,0.00083,1304,0.01820,990,0.01815
588596,Rhizophagus irregularis,S,1197,0.00791,627,0.00398,456,0.00150,552,0.00201,...,2747,0.00334,2022,0.00408,3147,0.00704,550,0.00768,518,0.00950

Columns: \
Sample num: Number of reads estimated for that species  \
Sample frac: Fraction of total reads in the sample estimated for this species \
[NOTE: Fractions are of total reads classified, unclassified reads not accounted for]

In [10]:
# Make taxa otu id table 
otu_id=otu_table.iloc[:, 0:2]
otu_id
# export otu id 
otu_id.to_csv("otu_id_species.csv")
#output to /bracken_ready

In [11]:
# drop name, taxa, and frac cols
drop_columns = [col for col in otu_table.columns if 'frac' in col]
drop_columns.extend(['name', 'taxonomy_lvl'])
otu_table_species=otu_table.drop(columns=drop_columns)

# rename to drop _num
#otu_table_species.columns.str.replace('_num', '')

# export otu table to csv
otu_table_species.to_csv("otu_table_species.csv")

I think I want to normalize based on number of reads classified for each sample (after filtering out human)

I previously normalized from total reads per sample, but then that includes all the unclassified reads as well as the human classified reads. As long as we are normalizing for differences in reads per sample I think this is better.

In [12]:
# add column for number of classified reads per sample
import re
slurmdir='/work/pi_sarah_gignouxwolfsohn_uml_edu/nikea/COL/slurms/slurm-bracken-filtering-S-60466011.out'
#make sure the order in which kraken.outs are merged are in the same order as the samplelist

In [ ]:
#This is the pattern in the slurm output I want to pull read #s from
# 242006 reads remaining (213219 reads excluded)

In [13]:
# Read the output report and extract the total number of reads
with open(slurmdir, 'r') as file:
    report_text = file.read()

In [14]:
# Extract total number of reads using regular expression
total_reads_pattern = re.compile(r'(\d+) reads remaining')
total_reads_matches = total_reads_pattern.findall(report_text)
total_reads_matches

['45477',
 '147935',
 '37335',
 '71650',
 '54541',
 '151278',
 '188260',
 '176733',
 '153011',
 '135850',
 '162967',
 '172085',
 '99881',
 '132344',
 '33922',
 '113427',
 '152080',
 '59988',
 '71412',
 '228879',
 '72399',
 '89331',
 '95734',
 '83244',
 '104361',
 '101845',
 '71866',
 '143209',
 '105263',
 '102262',
 '141730',
 '165255',
 '141166',
 '146080',
 '148457',
 '556869',
 '511221',
 '821439',
 '157638',
 '303419',
 '274615',
 '698554',
 '515815',
 '189288',
 '111256',
 '306505',
 '446880',
 '258106',
 '495207',
 '508142',
 '328034',
 '301469',
 '530702',
 '347489',
 '848485',
 '244065']

In [15]:
# Create a dictionary to map sample ID to total reads
total_reads_dict = {samplelist[i]: int(total_reads_matches[i]) for i in range(len(samplelist))}

# Display the updated DataFrame
print(total_reads_dict)

{'032024_COL_SAN_T5_139_OFAV_S17': 45477, '032024_COL_SAN_T5_140_OFAV_S18c': 147935, '032024_COL_SAN_T5_141_OFAV_S19': 37335, '032024_COL_SAN_T5_166_OFAV_S20': 71650, '032024_COL_SAN_T5_167_OFAV_S21': 54541, '012025_COL_SAN_T5_568_OFAV_S1': 151278, '012025_COL_SAN_T5_572_OFAV_S5': 188260, '012025_COL_SAN_T5_580_OFAV_S13': 176733, '012025_COL_SAN_T5_584_OFAV_S17': 153011, '012025_COL_SAN_T5_585_OFAV_S18': 135850, '012025_COL_SAN_T5_596_OFAV_S29': 162967, '032024_COL_SAN_T5_128_MCAV_S1': 172085, '032024_COL_SAN_T5_129_MCAV_S2': 99881, '032024_COL_SAN_T5_130_MCAV_S37': 132344, '032024_COL_SAN_T5_131_MCAV_S3': 33922, '032024_COL_SAN_T5_132_MCAV_S4': 113427, '032024_COL_SAN_T5_133_MCAV_S5': 152080, '032024_COL_SAN_T5_134_MCAV_S6': 59988, '032024_COL_SAN_T5_136_MCAV_S7': 71412, '032024_COL_SAN_T5_150_MCAV_S8': 228879, '012025_COL_SAN_T5_574_MCAV_S7': 72399, '012025_COL_SAN_T5_578_MCAV_S11': 89331, '012025_COL_SAN_T5_581_MCAV_S14': 95734, '012025_COL_SAN_T5_583_MCAV_S16': 83244, '012025_COL_SAN_T5_588_MCAV_S21': 104361, '012025_COL_SAN_T5_589_MCAV_S22': 101845, '012025_COL_SAN_T5_591_MCAV_S24': 71866, '012025_COL_SAN_T5_593_MCAV_S26': 143209, '012025_COL_SAN_T5_594_MCAV_S27': 105263, '012025_COL_SAN_T5_595_MCAV_S28': 102262, '032024_COL_SAN_T5_146_DLAB_S12': 141730, '032024_COL_SAN_T5_148_DLAB_S13': 165255, '032024_COL_SAN_T5_149_DLAB_S14': 141166, '032024_COL_SAN_T5_158_DLAB_S15': 146080, '032024_COL_SAN_T5_159_DLAB_S16': 148457, '032024_COL_SAN_T5_143_DLAB_S40': 556869, '032024_COL_SAN_T5_160_DLAB_S41': 511221, '032024_COL_SAN_T5_161_DLAB_S42': 821439, '012025_COL_SAN_T5_569_DLAB_S2': 157638, '012025_COL_SAN_T5_570_DLAB_S3': 303419, '012025_COL_SAN_T5_571_DLAB_S4': 274615, '012025_COL_SAN_T5_575_DLAB_S8': 698554, '012025_COL_SAN_T5_579_DLAB_S12': 515815, '012025_COL_SAN_T5_586_DLAB_S19': 189288, '032024_COL_SAN_T5_144_PSTR_S9': 111256, '032024_COL_SAN_T5_147_PSTR_S10': 306505, '032024_COL_SAN_T5_163_PSTR_S11c': 446880, '032024_COL_SAN_T5_154_PSTR_S38': 258106, '032024_COL_SAN_T5_162_PSTR_S39': 495207, '012025_COL_SAN_T5_573_PSTR_S6': 508142, '012025_COL_SAN_T5_576_PSTR_S9': 328034, '012025_COL_SAN_T5_577_PSTR_S10': 301469, '012025_COL_SAN_T5_582_PSTR_S15': 530702, '012025_COL_SAN_T5_587_PSTR_S20': 347489, '012025_COL_SAN_T5_590_PSTR_S23': 848485, '012025_COL_SAN_T5_592_PSTR_S25': 244065}

In [16]:
# Convert main df to raw abundances 
normalized_otus=otu_table.loc[:,otu_table.columns.str.contains("num")]
#headers in the otu table need to match the all_sampleids.txt
normalized_otus.columns = normalized_otus.columns.str.replace('_S_filt.bracken_num', '')
normalized_otus

,012025_COL_SAN_T5_568_OFAV_S1,012025_COL_SAN_T5_569_DLAB_S2,012025_COL_SAN_T5_570_DLAB_S3,012025_COL_SAN_T5_571_DLAB_S4,012025_COL_SAN_T5_572_OFAV_S5,012025_COL_SAN_T5_573_PSTR_S6,012025_COL_SAN_T5_574_MCAV_S7,012025_COL_SAN_T5_575_DLAB_S8,012025_COL_SAN_T5_576_PSTR_S9,012025_COL_SAN_T5_577_PSTR_S10,...,032024_COL_SAN_T5_150_MCAV_S8,032024_COL_SAN_T5_154_PSTR_S38,032024_COL_SAN_T5_158_DLAB_S15,032024_COL_SAN_T5_159_DLAB_S16,032024_COL_SAN_T5_160_DLAB_S41,032024_COL_SAN_T5_161_DLAB_S42,032024_COL_SAN_T5_162_PSTR_S39,032024_COL_SAN_T5_163_PSTR_S11c,032024_COL_SAN_T5_166_OFAV_S20,032024_COL_SAN_T5_167_OFAV_S21
taxonomy_id,,,,,,,,,,,,,,,,,,,,,
28213,4188,40,211,192,4103,172,2744,3910,21,43,...,20,0,0,0,0,145,0,3501,0,0
562,3624,1019,11006,23466,4078,2095,540,5482,1416,1316,...,1499,1682,931,1033,3076,13546,1884,2260,1923,1407
2961995,2234,0,55,0,664,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1830,958
2721244,1909,419,129,411,3105,271,195,754,227,312,...,241,241,379,349,801,295,324,372,1304,990
588596,1197,627,456,552,1381,1310,787,847,2666,2185,...,677,1410,1212,1328,2507,2747,2022,3147,550,518
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2956106,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,15,0,0
3059715,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,14,0,0
2675782,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,12,0,0
3040201,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,12,0,0
3050341,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,11,0,0

In [17]:
# Convert the dictionary to a DataFrame and transpose it
sample_counts_df = pd.DataFrame(total_reads_dict, index=['Total_reads'])
sample_counts_df

,032024_COL_SAN_T5_139_OFAV_S17,032024_COL_SAN_T5_140_OFAV_S18c,032024_COL_SAN_T5_141_OFAV_S19,032024_COL_SAN_T5_166_OFAV_S20,032024_COL_SAN_T5_167_OFAV_S21,012025_COL_SAN_T5_568_OFAV_S1,012025_COL_SAN_T5_572_OFAV_S5,012025_COL_SAN_T5_580_OFAV_S13,012025_COL_SAN_T5_584_OFAV_S17,012025_COL_SAN_T5_585_OFAV_S18,...,032024_COL_SAN_T5_163_PSTR_S11c,032024_COL_SAN_T5_154_PSTR_S38,032024_COL_SAN_T5_162_PSTR_S39,012025_COL_SAN_T5_573_PSTR_S6,012025_COL_SAN_T5_576_PSTR_S9,012025_COL_SAN_T5_577_PSTR_S10,012025_COL_SAN_T5_582_PSTR_S15,012025_COL_SAN_T5_587_PSTR_S20,012025_COL_SAN_T5_590_PSTR_S23,012025_COL_SAN_T5_592_PSTR_S25
Total_reads,45477,147935,37335,71650,54541,151278,188260,176733,153011,135850,...,446880,258106,495207,508142,328034,301469,530702,347489,848485,244065

In [18]:
# Concatenate the original DataFrame and the new DataFrame with the total reads row
normalized_otus = pd.concat([normalized_otus, sample_counts_df],axis=0)
normalized_otus

,012025_COL_SAN_T5_568_OFAV_S1,012025_COL_SAN_T5_569_DLAB_S2,012025_COL_SAN_T5_570_DLAB_S3,012025_COL_SAN_T5_571_DLAB_S4,012025_COL_SAN_T5_572_OFAV_S5,012025_COL_SAN_T5_573_PSTR_S6,012025_COL_SAN_T5_574_MCAV_S7,012025_COL_SAN_T5_575_DLAB_S8,012025_COL_SAN_T5_576_PSTR_S9,012025_COL_SAN_T5_577_PSTR_S10,...,032024_COL_SAN_T5_150_MCAV_S8,032024_COL_SAN_T5_154_PSTR_S38,032024_COL_SAN_T5_158_DLAB_S15,032024_COL_SAN_T5_159_DLAB_S16,032024_COL_SAN_T5_160_DLAB_S41,032024_COL_SAN_T5_161_DLAB_S42,032024_COL_SAN_T5_162_PSTR_S39,032024_COL_SAN_T5_163_PSTR_S11c,032024_COL_SAN_T5_166_OFAV_S20,032024_COL_SAN_T5_167_OFAV_S21
28213,4188,40,211,192,4103,172,2744,3910,21,43,...,20,0,0,0,0,145,0,3501,0,0
562,3624,1019,11006,23466,4078,2095,540,5482,1416,1316,...,1499,1682,931,1033,3076,13546,1884,2260,1923,1407
2961995,2234,0,55,0,664,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1830,958
2721244,1909,419,129,411,3105,271,195,754,227,312,...,241,241,379,349,801,295,324,372,1304,990
588596,1197,627,456,552,1381,1310,787,847,2666,2185,...,677,1410,1212,1328,2507,2747,2022,3147,550,518
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3059715,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,14,0,0
2675782,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,12,0,0
3040201,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,12,0,0
3050341,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,11,0,0
Total_reads,151278,157638,303419,274615,188260,508142,72399,698554,328034,301469,...,228879,258106,146080,148457,511221,821439,495207,446880,71650,54541

In [19]:
# Normalize: divide reads by total reads and multiply by 1 million
normalized_otu = (normalized_otus / normalized_otus.loc['Total_reads'] * 1E6)
# replace total reads row again 
normalized_otu.loc['Total_reads',:]=normalized_otus.loc['Total_reads',:]
normalized_otu["Sum"]=normalized_otu.sum(axis=1)
normalized_otu.sort_values(by="Sum", ascending=False)

,012025_COL_SAN_T5_568_OFAV_S1,012025_COL_SAN_T5_569_DLAB_S2,012025_COL_SAN_T5_570_DLAB_S3,012025_COL_SAN_T5_571_DLAB_S4,012025_COL_SAN_T5_572_OFAV_S5,012025_COL_SAN_T5_573_PSTR_S6,012025_COL_SAN_T5_574_MCAV_S7,012025_COL_SAN_T5_575_DLAB_S8,012025_COL_SAN_T5_576_PSTR_S9,012025_COL_SAN_T5_577_PSTR_S10,...,032024_COL_SAN_T5_154_PSTR_S38,032024_COL_SAN_T5_158_DLAB_S15,032024_COL_SAN_T5_159_DLAB_S16,032024_COL_SAN_T5_160_DLAB_S41,032024_COL_SAN_T5_161_DLAB_S42,032024_COL_SAN_T5_162_PSTR_S39,032024_COL_SAN_T5_163_PSTR_S11c,032024_COL_SAN_T5_166_OFAV_S20,032024_COL_SAN_T5_167_OFAV_S21,Sum
Total_reads,151278.000000,157638.000000,303419.000000,274615.000000,188260.000000,508142.000000,72399.000000,698554.000000,328034.000000,301469.000000,...,258106.000000,146080.000000,148457.000000,511221.000000,821439.000000,495207.000000,446880.000000,71650.000000,54541.000000,1.285646e+07
562,23955.895768,6464.177419,36273.272274,85450.539847,21661.531924,4122.863294,7458.666556,7847.639553,4316.625716,4365.291290,...,6516.702440,6373.220153,6958.243801,6016.967222,16490.573250,3804.469646,5057.286072,26838.799721,25797.106764,7.300561e+05
2057741,6517.801663,583.615626,2099.407091,542.577791,5359.609051,1538.939903,8895.150486,2104.346980,216.440979,408.002149,...,50448.265441,7516.429354,5705.355760,40049.215506,22055.198256,106517.072659,6800.483351,7690.160502,9350.763646,6.808883e+05
28213,27684.131202,253.745924,695.408000,699.160643,21794.326995,338.488060,37901.075982,5597.276660,64.017754,142.634898,...,0.000000,0.000000,0.000000,0.000000,176.519498,0.000000,7834.317938,0.000000,0.000000,5.546384e+05
2653203,2359.893706,43434.958576,111565.195324,109036.287166,3410.177414,56480.275199,2955.841932,5101.967779,10715.352677,19866.055880,...,0.000000,0.000000,0.000000,21.517113,108.346451,26.251648,138.739706,0.000000,0.000000,4.517968e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1967296,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.178571e+01
2216012,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.178571e+01
67313,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.178571e+01
2876193,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.178571e+01
2956679,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.178571e+01

In [20]:
# export otu table to csv
normalized_otu.to_csv("otu_normtable_species.csv")

This otu table still has Total_reads row and Sum column. These should be removed and add taxonomy_id label to the first column

**this notebook stops here, below is code from DR analysis in case I want to do this with COL data, delete if I decide not to**

### Now let's do Kindgom level

starting at step 7: reading in the kingdom otu table this time

In [21]:
otu_table_k=pd.read_csv("/scratch4/workspace/nikea_ulrich_uml_edu-col_data/kraken2_pluspf/bracken_ready/all_merged_bracken_K.txt", sep='\t')

In [22]:
otu_table_k.set_index("taxonomy_id",inplace=True)

In [23]:
otu_table_k.head()

,name,taxonomy_lvl,012025_COL_SAN_T5_568_OFAV_S1_K_filt.bracken_num,012025_COL_SAN_T5_568_OFAV_S1_K_filt.bracken_frac,012025_COL_SAN_T5_569_DLAB_S2_K_filt.bracken_num,012025_COL_SAN_T5_569_DLAB_S2_K_filt.bracken_frac,012025_COL_SAN_T5_570_DLAB_S3_K_filt.bracken_num,012025_COL_SAN_T5_570_DLAB_S3_K_filt.bracken_frac,012025_COL_SAN_T5_571_DLAB_S4_K_filt.bracken_num,012025_COL_SAN_T5_571_DLAB_S4_K_filt.bracken_frac,...,032024_COL_SAN_T5_161_DLAB_S42_K_filt.bracken_num,032024_COL_SAN_T5_161_DLAB_S42_K_filt.bracken_frac,032024_COL_SAN_T5_162_PSTR_S39_K_filt.bracken_num,032024_COL_SAN_T5_162_PSTR_S39_K_filt.bracken_frac,032024_COL_SAN_T5_163_PSTR_S11c_K_filt.bracken_num,032024_COL_SAN_T5_163_PSTR_S11c_K_filt.bracken_frac,032024_COL_SAN_T5_166_OFAV_S20_K_filt.bracken_num,032024_COL_SAN_T5_166_OFAV_S20_K_filt.bracken_frac,032024_COL_SAN_T5_167_OFAV_S21_K_filt.bracken_num,032024_COL_SAN_T5_167_OFAV_S21_K_filt.bracken_frac
taxonomy_id,,,,,,,,,,,,,,,,,,,,,
3379134,Pseudomonadati,K,98123,0.57201,116911,0.61280,256304,0.76466,219050,0.71284,...,565185,0.66861,344546,0.65912,273782,0.58007,58799,0.60381,40257,0.54577
1783272,Bacillati,K,53125,0.30969,55416,0.29047,63772,0.19026,73268,0.23843,...,213516,0.25259,128265,0.24537,141518,0.29984,28449,0.29214,24263,0.32894
4751,Fungi,K,13956,0.08136,11708,0.06137,10012,0.02987,9799,0.03189,...,45852,0.05424,34681,0.06634,39387,0.08345,6969,0.07157,6372,0.08639
3366610,Methanobacteriati,K,2491,0.01452,2040,0.01069,1615,0.00482,1902,0.00619,...,7160,0.00847,5388,0.01031,5917,0.01254,1175,0.01207,1061,0.01438
3384189,Fusobacteriati,K,1094,0.00638,1740,0.00912,1115,0.00333,903,0.00294,...,3881,0.00459,2909,0.00556,3245,0.00688,548,0.00563,562,0.00762

In [24]:
# Make taxa otu id table 
otu_id_k=otu_table_k.iloc[:, 0:2]
otu_id_k
# export otu id 
otu_id_k.to_csv("otu_id_kingdom.csv")
#output to /bracken_ready

In [25]:
# drop name, taxa, and frac cols
drop_columns = [col for col in otu_table_k.columns if 'frac' in col]
drop_columns.extend(['name', 'taxonomy_lvl'])
otu_table_kingdom=otu_table_k.drop(columns=drop_columns)

# rename to drop _num
#otu_table_species.columns.str.replace('_num', '')

# export otu table to csv
otu_table_kingdom.to_csv("otu_table_kingdom.csv")

In [26]:
# add column for number of classified reads per sample
import re
slurmdir_k='/work/pi_sarah_gignouxwolfsohn_uml_edu/nikea/COL/slurms/slurm-bracken-filtering-K-60466012.out'
#make sure the order in which kraken.outs are merged are in the same order as the samplelist

In [27]:
# Read the output report and extract the total number of reads
with open(slurmdir_k, 'r') as file:
    report_text = file.read()

In [28]:
# Extract total number of reads using regular expression
total_reads_pattern = re.compile(r'(\d+) reads remaining')
total_reads_matches = total_reads_pattern.findall(report_text)
total_reads_matches

['63073',
 '166859',
 '55370',
 '97380',
 '73762',
 '171541',
 '211148',
 '198441',
 '171290',
 '156442',
 '183987',
 '195020',
 '127199',
 '159836',
 '53830',
 '133588',
 '174291',
 '81143',
 '91935',
 '260571',
 '92879',
 '116273',
 '115910',
 '103917',
 '133579',
 '122899',
 '99956',
 '171166',
 '124983',
 '126770',
 '167098',
 '193957',
 '166949',
 '171560',
 '174130',
 '580822',
 '537887',
 '845311',
 '190783',
 '335187',
 '307293',
 '722959',
 '545284',
 '220170',
 '134891',
 '335670',
 '471985',
 '285070',
 '522740',
 '536720',
 '352497',
 '330487',
 '554807',
 '371072',
 '869521',
 '272582']

In [29]:
# Create a dictionary to map sample ID to total reads
total_reads_dict = {samplelist[i]: int(total_reads_matches[i]) for i in range(len(samplelist))}

# Display the updated DataFrame
print(total_reads_dict)

{'032024_COL_SAN_T5_139_OFAV_S17': 63073, '032024_COL_SAN_T5_140_OFAV_S18c': 166859, '032024_COL_SAN_T5_141_OFAV_S19': 55370, '032024_COL_SAN_T5_166_OFAV_S20': 97380, '032024_COL_SAN_T5_167_OFAV_S21': 73762, '012025_COL_SAN_T5_568_OFAV_S1': 171541, '012025_COL_SAN_T5_572_OFAV_S5': 211148, '012025_COL_SAN_T5_580_OFAV_S13': 198441, '012025_COL_SAN_T5_584_OFAV_S17': 171290, '012025_COL_SAN_T5_585_OFAV_S18': 156442, '012025_COL_SAN_T5_596_OFAV_S29': 183987, '032024_COL_SAN_T5_128_MCAV_S1': 195020, '032024_COL_SAN_T5_129_MCAV_S2': 127199, '032024_COL_SAN_T5_130_MCAV_S37': 159836, '032024_COL_SAN_T5_131_MCAV_S3': 53830, '032024_COL_SAN_T5_132_MCAV_S4': 133588, '032024_COL_SAN_T5_133_MCAV_S5': 174291, '032024_COL_SAN_T5_134_MCAV_S6': 81143, '032024_COL_SAN_T5_136_MCAV_S7': 91935, '032024_COL_SAN_T5_150_MCAV_S8': 260571, '012025_COL_SAN_T5_574_MCAV_S7': 92879, '012025_COL_SAN_T5_578_MCAV_S11': 116273, '012025_COL_SAN_T5_581_MCAV_S14': 115910, '012025_COL_SAN_T5_583_MCAV_S16': 103917, '012025_COL_SAN_T5_588_MCAV_S21': 133579, '012025_COL_SAN_T5_589_MCAV_S22': 122899, '012025_COL_SAN_T5_591_MCAV_S24': 99956, '012025_COL_SAN_T5_593_MCAV_S26': 171166, '012025_COL_SAN_T5_594_MCAV_S27': 124983, '012025_COL_SAN_T5_595_MCAV_S28': 126770, '032024_COL_SAN_T5_146_DLAB_S12': 167098, '032024_COL_SAN_T5_148_DLAB_S13': 193957, '032024_COL_SAN_T5_149_DLAB_S14': 166949, '032024_COL_SAN_T5_158_DLAB_S15': 171560, '032024_COL_SAN_T5_159_DLAB_S16': 174130, '032024_COL_SAN_T5_143_DLAB_S40': 580822, '032024_COL_SAN_T5_160_DLAB_S41': 537887, '032024_COL_SAN_T5_161_DLAB_S42': 845311, '012025_COL_SAN_T5_569_DLAB_S2': 190783, '012025_COL_SAN_T5_570_DLAB_S3': 335187, '012025_COL_SAN_T5_571_DLAB_S4': 307293, '012025_COL_SAN_T5_575_DLAB_S8': 722959, '012025_COL_SAN_T5_579_DLAB_S12': 545284, '012025_COL_SAN_T5_586_DLAB_S19': 220170, '032024_COL_SAN_T5_144_PSTR_S9': 134891, '032024_COL_SAN_T5_147_PSTR_S10': 335670, '032024_COL_SAN_T5_163_PSTR_S11c': 471985, '032024_COL_SAN_T5_154_PSTR_S38': 285070, '032024_COL_SAN_T5_162_PSTR_S39': 522740, '012025_COL_SAN_T5_573_PSTR_S6': 536720, '012025_COL_SAN_T5_576_PSTR_S9': 352497, '012025_COL_SAN_T5_577_PSTR_S10': 330487, '012025_COL_SAN_T5_582_PSTR_S15': 554807, '012025_COL_SAN_T5_587_PSTR_S20': 371072, '012025_COL_SAN_T5_590_PSTR_S23': 869521, '012025_COL_SAN_T5_592_PSTR_S25': 272582}

In [30]:
# Convert main df to raw abundances 
normalized_otus_k=otu_table_k.loc[:,otu_table_k.columns.str.contains("num")]
#headers in the otu table need to match the all_sampleids.txt
normalized_otus_k.columns = normalized_otus_k.columns.str.replace('_K_filt.bracken_num', '')
normalized_otus_k

,012025_COL_SAN_T5_568_OFAV_S1,012025_COL_SAN_T5_569_DLAB_S2,012025_COL_SAN_T5_570_DLAB_S3,012025_COL_SAN_T5_571_DLAB_S4,012025_COL_SAN_T5_572_OFAV_S5,012025_COL_SAN_T5_573_PSTR_S6,012025_COL_SAN_T5_574_MCAV_S7,012025_COL_SAN_T5_575_DLAB_S8,012025_COL_SAN_T5_576_PSTR_S9,012025_COL_SAN_T5_577_PSTR_S10,...,032024_COL_SAN_T5_150_MCAV_S8,032024_COL_SAN_T5_154_PSTR_S38,032024_COL_SAN_T5_158_DLAB_S15,032024_COL_SAN_T5_159_DLAB_S16,032024_COL_SAN_T5_160_DLAB_S41,032024_COL_SAN_T5_161_DLAB_S42,032024_COL_SAN_T5_162_PSTR_S39,032024_COL_SAN_T5_163_PSTR_S11c,032024_COL_SAN_T5_166_OFAV_S20,032024_COL_SAN_T5_167_OFAV_S21
taxonomy_id,,,,,,,,,,,,,,,,,,,,,
3379134,98123,116911,256304,219050,118197,385171,50870,512974,200163,186816,...,189545,170738,91463,88441,309319,565185,344546,273782,58799,40257
1783272,53125,55416,63772,73268,66983,118786,29423,180947,107539,104184,...,57861,81042,55836,59648,164541,213516,128265,141518,28449,24263
4751,13956,11708,10012,9799,18126,22152,8867,19026,31305,27663,...,8359,23618,16555,18100,41587,45852,34681,39387,6969,6372
3366610,2491,2040,1615,1902,3012,4032,1168,4881,4699,4134,...,1821,3972,2745,2467,5779,7160,5388,5917,1175,1061
3384189,1094,1740,1115,903,1252,1837,745,1225,2581,2164,...,1019,1494,1525,1775,4507,3881,2909,3245,548,562
1783275,766,1675,472,452,1054,1559,586,612,1854,2131,...,451,1165,1048,1395,3337,3263,2201,2444,400,354
2731360,739,332,995,908,1027,1333,252,805,1363,972,...,332,1185,798,922,2159,2364,1515,1765,372,370
2732005,565,226,185,221,456,343,312,333,699,597,...,258,341,524,451,872,847,563,910,222,208
3384194,469,537,598,581,728,1207,331,1722,1396,1218,...,696,945,764,664,4896,2226,1983,1832,313,239
2732396,111,95,82,100,143,197,121,175,390,238,...,77,226,194,150,333,371,305,492,72,43
1935183,79,16,15,16,129,34,38,30,98,83,...,42,49,77,75,131,146,78,134,35,33
2840023,13,18,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2732092,10,0,0,0,26,45,25,0,44,29,...,0,49,12,21,39,50,66,70,13,0
2732397,0,69,0,93,0,0,105,205,322,236,...,81,225,0,0,343,399,216,429,0,0
1783276,0,0,22,0,15,24,36,24,44,22,...,29,21,19,21,44,51,24,60,13,0

In [31]:
# Convert the dictionary to a DataFrame and transpose it
sample_counts_df_k = pd.DataFrame(total_reads_dict, index=['Total_reads'])
sample_counts_df_k

,032024_COL_SAN_T5_139_OFAV_S17,032024_COL_SAN_T5_140_OFAV_S18c,032024_COL_SAN_T5_141_OFAV_S19,032024_COL_SAN_T5_166_OFAV_S20,032024_COL_SAN_T5_167_OFAV_S21,012025_COL_SAN_T5_568_OFAV_S1,012025_COL_SAN_T5_572_OFAV_S5,012025_COL_SAN_T5_580_OFAV_S13,012025_COL_SAN_T5_584_OFAV_S17,012025_COL_SAN_T5_585_OFAV_S18,...,032024_COL_SAN_T5_163_PSTR_S11c,032024_COL_SAN_T5_154_PSTR_S38,032024_COL_SAN_T5_162_PSTR_S39,012025_COL_SAN_T5_573_PSTR_S6,012025_COL_SAN_T5_576_PSTR_S9,012025_COL_SAN_T5_577_PSTR_S10,012025_COL_SAN_T5_582_PSTR_S15,012025_COL_SAN_T5_587_PSTR_S20,012025_COL_SAN_T5_590_PSTR_S23,012025_COL_SAN_T5_592_PSTR_S25
Total_reads,63073,166859,55370,97380,73762,171541,211148,198441,171290,156442,...,471985,285070,522740,536720,352497,330487,554807,371072,869521,272582

In [32]:
# Concatenate the original DataFrame and the new DataFrame with the total reads row
normalized_otus_k = pd.concat([normalized_otus_k, sample_counts_df_k],axis=0)
normalized_otus_k

,012025_COL_SAN_T5_568_OFAV_S1,012025_COL_SAN_T5_569_DLAB_S2,012025_COL_SAN_T5_570_DLAB_S3,012025_COL_SAN_T5_571_DLAB_S4,012025_COL_SAN_T5_572_OFAV_S5,012025_COL_SAN_T5_573_PSTR_S6,012025_COL_SAN_T5_574_MCAV_S7,012025_COL_SAN_T5_575_DLAB_S8,012025_COL_SAN_T5_576_PSTR_S9,012025_COL_SAN_T5_577_PSTR_S10,...,032024_COL_SAN_T5_150_MCAV_S8,032024_COL_SAN_T5_154_PSTR_S38,032024_COL_SAN_T5_158_DLAB_S15,032024_COL_SAN_T5_159_DLAB_S16,032024_COL_SAN_T5_160_DLAB_S41,032024_COL_SAN_T5_161_DLAB_S42,032024_COL_SAN_T5_162_PSTR_S39,032024_COL_SAN_T5_163_PSTR_S11c,032024_COL_SAN_T5_166_OFAV_S20,032024_COL_SAN_T5_167_OFAV_S21
3379134,98123,116911,256304,219050,118197,385171,50870,512974,200163,186816,...,189545,170738,91463,88441,309319,565185,344546,273782,58799,40257
1783272,53125,55416,63772,73268,66983,118786,29423,180947,107539,104184,...,57861,81042,55836,59648,164541,213516,128265,141518,28449,24263
4751,13956,11708,10012,9799,18126,22152,8867,19026,31305,27663,...,8359,23618,16555,18100,41587,45852,34681,39387,6969,6372
3366610,2491,2040,1615,1902,3012,4032,1168,4881,4699,4134,...,1821,3972,2745,2467,5779,7160,5388,5917,1175,1061
3384189,1094,1740,1115,903,1252,1837,745,1225,2581,2164,...,1019,1494,1525,1775,4507,3881,2909,3245,548,562
1783275,766,1675,472,452,1054,1559,586,612,1854,2131,...,451,1165,1048,1395,3337,3263,2201,2444,400,354
2731360,739,332,995,908,1027,1333,252,805,1363,972,...,332,1185,798,922,2159,2364,1515,1765,372,370
2732005,565,226,185,221,456,343,312,333,699,597,...,258,341,524,451,872,847,563,910,222,208
3384194,469,537,598,581,728,1207,331,1722,1396,1218,...,696,945,764,664,4896,2226,1983,1832,313,239
2732396,111,95,82,100,143,197,121,175,390,238,...,77,226,194,150,333,371,305,492,72,43
1935183,79,16,15,16,129,34,38,30,98,83,...,42,49,77,75,131,146,78,134,35,33
2840023,13,18,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2732092,10,0,0,0,26,45,25,0,44,29,...,0,49,12,21,39,50,66,70,13,0
2732397,0,69,0,93,0,0,105,205,322,236,...,81,225,0,0,343,399,216,429,0,0
1783276,0,0,22,0,15,24,36,24,44,22,...,29,21,19,21,44,51,24,60,13,0
Total_reads,171541,190783,335187,307293,211148,536720,92879,722959,352497,330487,...,260571,285070,171560,174130,537887,845311,522740,471985,97380,73762

something weird is happening. Total reads should have the most in each sample, not a taxID. Ok it is doing the math correctly but then not replacing the total reads row with new sum. That's ok, will be removing the total reads column anyway

In [33]:
# Normalize: divide reads by total reads and multiply by 1 million
normalized_otu_k = (normalized_otus_k / normalized_otus_k.loc['Total_reads'] * 1E6)
# replace total reads row again 
normalized_otu_k.loc['Total_reads',:]=normalized_otus_k.loc['Total_reads',:]
normalized_otu_k["Sum"]=normalized_otu_k.sum(axis=1)
normalized_otu_k.sort_values(by="Sum", ascending=False)

,012025_COL_SAN_T5_568_OFAV_S1,012025_COL_SAN_T5_569_DLAB_S2,012025_COL_SAN_T5_570_DLAB_S3,012025_COL_SAN_T5_571_DLAB_S4,012025_COL_SAN_T5_572_OFAV_S5,012025_COL_SAN_T5_573_PSTR_S6,012025_COL_SAN_T5_574_MCAV_S7,012025_COL_SAN_T5_575_DLAB_S8,012025_COL_SAN_T5_576_PSTR_S9,012025_COL_SAN_T5_577_PSTR_S10,...,032024_COL_SAN_T5_154_PSTR_S38,032024_COL_SAN_T5_158_DLAB_S15,032024_COL_SAN_T5_159_DLAB_S16,032024_COL_SAN_T5_160_DLAB_S41,032024_COL_SAN_T5_161_DLAB_S42,032024_COL_SAN_T5_162_PSTR_S39,032024_COL_SAN_T5_163_PSTR_S11c,032024_COL_SAN_T5_166_OFAV_S20,032024_COL_SAN_T5_167_OFAV_S21,Sum
3379134,572009.024082,612795.689343,764659.727257,712837.584976,559782.711652,717638.619764,547701.848642,709547.844345,567843.130580,565274.882219,...,598933.595257,533125.437165,507902.142078,575063.163824,668611.907334,659115.430233,580065.044440,603809.817211,545768.824056,3.205614e+07
1783272,309692.726520,290466.131678,190257.975399,238430.423082,317232.462538,221318.378298,316788.509782,250286.669092,305077.773712,315243.867384,...,284288.069597,325460.480298,342548.670534,305902.540868,252588.692209,245370.547500,299835.799867,292144.177449,328936.308668,1.756187e+07
Total_reads,171541.000000,190783.000000,335187.000000,307293.000000,211148.000000,536720.000000,92879.000000,722959.000000,352497.000000,330487.000000,...,285070.000000,171560.000000,174130.000000,537887.000000,845311.000000,522740.000000,471985.000000,97380.000000,73762.000000,1.423247e+07
4751,81356.643601,61368.151250,29869.893522,31888.132824,85844.999716,41272.916977,95468.297462,26316.845077,88809.266462,83703.746290,...,82849.826358,96496.852413,103945.328203,77315.495634,54242.757991,66344.645522,83449.685901,71565.003081,86385.943982,4.425403e+06
3366610,14521.309774,10692.776610,4818.205957,6189.532466,14264.875822,7512.296915,12575.501459,6751.420205,13330.609906,12508.812752,...,13933.419862,16000.233155,14167.575949,10743.892305,8470.255326,10307.227302,12536.415352,12066.132676,14384.100214,6.936252e+05
3384189,6377.484100,9120.309462,3326.501326,2938.563521,5929.490215,3422.641228,8021.188859,1694.425272,7322.048131,6547.912626,...,5240.818045,8889.018419,10193.533567,8379.083339,4591.209626,5564.907985,6875.218492,5627.438899,7619.099265,4.015504e+05
1783275,4465.404772,8779.608246,1408.169171,1470.908872,4991.759335,2904.680280,6309.284122,846.521034,5259.619231,6448.059984,...,4086.715544,6108.650035,8011.255958,6203.905281,3860.117755,4210.506179,5178.130661,4107.619634,4799.219110,2.570923e+05
3384194,2734.040259,2814.716196,1784.078738,1890.703661,3447.818592,2248.844835,3563.776526,2381.877810,3960.317393,3685.470230,...,3314.975269,4453.252506,3813.242979,9102.283565,2633.350329,3793.472855,3881.479284,3214.212364,3240.150755,1.954821e+05
2731360,4308.007998,1740.196978,2968.492215,2954.834637,4863.886942,2483.604114,2713.207507,1113.479464,3866.699575,2941.114174,...,4156.873750,4651.433901,5294.894619,4013.854211,2796.603853,2898.190305,3739.525621,3820.086260,5016.132968,1.932978e+05
2732005,3293.673233,1184.591919,551.930713,719.183320,2159.622634,639.066925,3359.209294,460.607033,1982.995600,1806.425064,...,1196.197425,3054.325017,2590.018951,1621.158347,1001.998081,1077.017255,1928.027374,2279.728897,2819.880155,1.188164e+05
2732396,647.075626,497.947930,244.639559,325.422317,677.250081,367.044269,1302.770271,242.060753,1106.392395,720.149355,...,792.787736,1130.799720,861.425372,619.089140,438.891722,583.464055,1042.406009,739.371534,582.955994,4.441535e+04
2732397,0.000000,361.667444,0.000000,302.642755,0.000000,0.000000,1130.503128,283.556882,913.482952,714.097680,...,789.279826,0.000000,0.000000,637.680405,472.015625,413.207331,908.927190,0.000000,0.000000,1.892072e+04
1935183,460.531302,83.864915,44.751139,52.067571,610.945877,63.347742,409.134465,41.496129,278.016550,251.144523,...,171.887607,448.822569,430.712686,243.545577,172.717497,149.213758,283.907328,359.416718,447.384832,1.651819e+04
2732092,58.295101,0.000000,0.000000,0.000000,123.136378,83.842599,269.167411,0.000000,124.823757,87.749291,...,171.887607,69.946374,120.599552,72.505935,59.149828,126.257795,148.309798,133.497638,0.000000,7.735025e+03
1783276,0.000000,0.000000,65.635004,0.000000,71.040218,44.716053,387.601072,33.196903,124.823757,66.568428,...,73.666117,110.748426,120.599552,81.801568,60.332824,45.911926,127.122684,133.497638,0.000000,7.623732e+03
2840023,75.783632,94.348029,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.512510e+03

In [34]:
# export otu table to csv
normalized_otu_k.to_csv("otu_normtable_kingdom.csv")