### Converting bracken output to normalized ASV table

#### let's start with species level

In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
import os

In [5]:
os.chdir('/work/pi_sarah_gignouxwolfsohn_uml_edu/nikea/COL/ID_tables')

In [6]:
os.chdir('/scratch4/workspace/nikea_ulrich_uml_edu-col_data/kraken2_pluspf/bracken_ready')

In [7]:
# Set path variables and create sample list 
SAMPLES='/work/pi_sarah_gignouxwolfsohn_uml_edu/nikea/COL/ID_tables/all_sampleids.txt'
BRACKENS='/scratch4/workspace/nikea_ulrich_uml_edu-col_data/kraken2_pluspf/bracken_filtered'
samplelist=[]

with open(SAMPLES) as samples:
    for line in samples:
        samplelist.append(line.strip())
print(samplelist)

sample_names_string = ','.join(samplelist)
print(sample_names_string)
print(len(samplelist))

['032024_COL_SAN_T5_139_OFAV_S17', '032024_COL_SAN_T5_140_OFAV_S18c', '032024_COL_SAN_T5_141_OFAV_S19', '032024_COL_SAN_T5_166_OFAV_S20', '032024_COL_SAN_T5_167_OFAV_S21', '012025_COL_SAN_T5_568_OFAV_S1', '012025_COL_SAN_T5_572_OFAV_S5', '012025_COL_SAN_T5_580_OFAV_S13', '012025_COL_SAN_T5_584_OFAV_S17', '012025_COL_SAN_T5_585_OFAV_S18', '012025_COL_SAN_T5_596_OFAV_S29', '032024_COL_SAN_T5_128_MCAV_S1', '032024_COL_SAN_T5_129_MCAV_S2', '032024_COL_SAN_T5_130_MCAV_S37', '032024_COL_SAN_T5_131_MCAV_S3', '032024_COL_SAN_T5_132_MCAV_S4', '032024_COL_SAN_T5_133_MCAV_S5', '032024_COL_SAN_T5_134_MCAV_S6', '032024_COL_SAN_T5_136_MCAV_S7', '032024_COL_SAN_T5_150_MCAV_S8', '012025_COL_SAN_T5_574_MCAV_S7', '012025_COL_SAN_T5_578_MCAV_S11', '012025_COL_SAN_T5_581_MCAV_S14', '012025_COL_SAN_T5_583_MCAV_S16', '012025_COL_SAN_T5_588_MCAV_S21', '012025_COL_SAN_T5_589_MCAV_S22', '012025_COL_SAN_T5_591_MCAV_S24', '012025_COL_SAN_T5_593_MCAV_S26', '012025_COL_SAN_T5_594_MCAV_S27', '012025_COL_SAN_T5_595_MCAV_S28', '032024_COL_SAN_T5_146_DLAB_S12', '032024_COL_SAN_T5_148_DLAB_S13', '032024_COL_SAN_T5_149_DLAB_S14', '032024_COL_SAN_T5_158_DLAB_S15', '032024_COL_SAN_T5_159_DLAB_S16', '032024_COL_SAN_T5_143_DLAB_S40', '032024_COL_SAN_T5_160_DLAB_S41', '032024_COL_SAN_T5_161_DLAB_S42', '012025_COL_SAN_T5_569_DLAB_S2', '012025_COL_SAN_T5_570_DLAB_S3', '012025_COL_SAN_T5_571_DLAB_S4', '012025_COL_SAN_T5_575_DLAB_S8', '012025_COL_SAN_T5_579_DLAB_S12', '012025_COL_SAN_T5_586_DLAB_S19', '032024_COL_SAN_T5_144_PSTR_S9', '032024_COL_SAN_T5_147_PSTR_S10', '032024_COL_SAN_T5_163_PSTR_S11c', '032024_COL_SAN_T5_154_PSTR_S38', '032024_COL_SAN_T5_162_PSTR_S39', '012025_COL_SAN_T5_573_PSTR_S6', '012025_COL_SAN_T5_576_PSTR_S9', '012025_COL_SAN_T5_577_PSTR_S10', '012025_COL_SAN_T5_582_PSTR_S15', '012025_COL_SAN_T5_587_PSTR_S20', '012025_COL_SAN_T5_590_PSTR_S23', '012025_COL_SAN_T5_592_PSTR_S25']
032024_COL_SAN_T5_139_OFAV_S17,032024_COL_SAN_T5_140_OFAV_S18c,032024_COL_SAN_T5_141_OFAV_S19,032024_COL_SAN_T5_166_OFAV_S20,032024_COL_SAN_T5_167_OFAV_S21,012025_COL_SAN_T5_568_OFAV_S1,012025_COL_SAN_T5_572_OFAV_S5,012025_COL_SAN_T5_580_OFAV_S13,012025_COL_SAN_T5_584_OFAV_S17,012025_COL_SAN_T5_585_OFAV_S18,012025_COL_SAN_T5_596_OFAV_S29,032024_COL_SAN_T5_128_MCAV_S1,032024_COL_SAN_T5_129_MCAV_S2,032024_COL_SAN_T5_130_MCAV_S37,032024_COL_SAN_T5_131_MCAV_S3,032024_COL_SAN_T5_132_MCAV_S4,032024_COL_SAN_T5_133_MCAV_S5,032024_COL_SAN_T5_134_MCAV_S6,032024_COL_SAN_T5_136_MCAV_S7,032024_COL_SAN_T5_150_MCAV_S8,012025_COL_SAN_T5_574_MCAV_S7,012025_COL_SAN_T5_578_MCAV_S11,012025_COL_SAN_T5_581_MCAV_S14,012025_COL_SAN_T5_583_MCAV_S16,012025_COL_SAN_T5_588_MCAV_S21,012025_COL_SAN_T5_589_MCAV_S22,012025_COL_SAN_T5_591_MCAV_S24,012025_COL_SAN_T5_593_MCAV_S26,012025_COL_SAN_T5_594_MCAV_S27,012025_COL_SAN_T5_595_MCAV_S28,032024_COL_SAN_T5_146_DLAB_S12,032024_COL_SAN_T5_148_DLAB_S13,032024_COL_SAN_T5_149_DLAB_S14,032024_COL_SAN_T5_158_DLAB_S15,032024_COL_SAN_T5_159_DLAB_S16,032024_COL_SAN_T5_143_DLAB_S40,032024_COL_SAN_T5_160_DLAB_S41,032024_COL_SAN_T5_161_DLAB_S42,012025_COL_SAN_T5_569_DLAB_S2,012025_COL_SAN_T5_570_DLAB_S3,012025_COL_SAN_T5_571_DLAB_S4,012025_COL_SAN_T5_575_DLAB_S8,012025_COL_SAN_T5_579_DLAB_S12,012025_COL_SAN_T5_586_DLAB_S19,032024_COL_SAN_T5_144_PSTR_S9,032024_COL_SAN_T5_147_PSTR_S10,032024_COL_SAN_T5_163_PSTR_S11c,032024_COL_SAN_T5_154_PSTR_S38,032024_COL_SAN_T5_162_PSTR_S39,012025_COL_SAN_T5_573_PSTR_S6,012025_COL_SAN_T5_576_PSTR_S9,012025_COL_SAN_T5_577_PSTR_S10,012025_COL_SAN_T5_582_PSTR_S15,012025_COL_SAN_T5_587_PSTR_S20,012025_COL_SAN_T5_590_PSTR_S23,012025_COL_SAN_T5_592_PSTR_S25
56

In [19]:
otu_table=pd.read_csv("/scratch4/workspace/nikea_ulrich_uml_edu-col_data/kraken2_pluspf/bracken_ready/all_merged_bracken_S.txt", sep='\t')

In [20]:
otu_table.set_index("taxonomy_id",inplace=True)

In [21]:
otu_table.head()

,name,taxonomy_lvl,012025_COL_SAN_T5_568_OFAV_S1_S_filt.bracken_num,012025_COL_SAN_T5_568_OFAV_S1_S_filt.bracken_frac,012025_COL_SAN_T5_569_DLAB_S2_S_filt.bracken_num,012025_COL_SAN_T5_569_DLAB_S2_S_filt.bracken_frac,012025_COL_SAN_T5_570_DLAB_S3_S_filt.bracken_num,012025_COL_SAN_T5_570_DLAB_S3_S_filt.bracken_frac,012025_COL_SAN_T5_571_DLAB_S4_S_filt.bracken_num,012025_COL_SAN_T5_571_DLAB_S4_S_filt.bracken_frac,...,032024_COL_SAN_T5_161_DLAB_S42_S_filt.bracken_num,032024_COL_SAN_T5_161_DLAB_S42_S_filt.bracken_frac,032024_COL_SAN_T5_162_PSTR_S39_S_filt.bracken_num,032024_COL_SAN_T5_162_PSTR_S39_S_filt.bracken_frac,032024_COL_SAN_T5_163_PSTR_S11c_S_filt.bracken_num,032024_COL_SAN_T5_163_PSTR_S11c_S_filt.bracken_frac,032024_COL_SAN_T5_166_OFAV_S20_S_filt.bracken_num,032024_COL_SAN_T5_166_OFAV_S20_S_filt.bracken_frac,032024_COL_SAN_T5_167_OFAV_S21_S_filt.bracken_num,032024_COL_SAN_T5_167_OFAV_S21_S_filt.bracken_frac
taxonomy_id,,,,,,,,,,,,,,,,,,,,,
562,Escherichia coli,S,8767,0.02940,1165,0.00591,9657,0.02516,20235,0.06319,...,13813,0.01447,2475,0.00433,3867,0.00427,5016,0.03242,3735,0.02910
28213,Sphingomonas parapaucimobilis,S,4039,0.01355,42,0.00021,206,0.00054,198,0.00062,...,98,0.00010,0,0.00000,3322,0.00367,0,0.00000,0,0.00000
573,Klebsiella pneumoniae,S,1918,0.00643,912,0.00463,841,0.00219,1035,0.00323,...,2405,0.00252,1289,0.00225,2891,0.00319,1497,0.00967,902,0.00703
2721244,Streptomyces sp. RPA4-2,S,1700,0.00570,224,0.00114,68,0.00018,283,0.00088,...,201,0.00021,213,0.00037,324,0.00036,1000,0.00646,917,0.00715
238834,Clostridium estertheticum,S,1618,0.00543,141,0.00072,234,0.00061,158,0.00049,...,784,0.00082,569,0.00099,1098,0.00121,716,0.00463,743,0.00579

Columns: \
Sample num: Number of reads estimated for that species  \
Sample frac: Fraction of total reads in the sample estimated for this species \
[NOTE: Fractions are of total reads classified, unclassified reads not accounted for]

In [22]:
# Make taxa otu id table 
otu_id=otu_table.iloc[:, 0:2]
otu_id
# export otu id 
otu_id.to_csv("otu_id_species.csv")
#output to /bracken_filtered

In [23]:
# drop name, taxa, and frac cols
drop_columns = [col for col in otu_table.columns if 'frac' in col]
drop_columns.extend(['name', 'taxonomy_lvl'])
otu_table_species=otu_table.drop(columns=drop_columns)

# rename to drop _num
#otu_table_species.columns.str.replace('_num', '')

# export otu table to csv
otu_table_species.to_csv("otu_table_species.csv")

I think I want to normalize based on number of reads classified for each sample (after filtering out human)

I previously normalized from total reads per sample, but then that includes all the unclassified reads as well as the human classified reads. As long as we are normalizing for differences in reads per sample I think this is better.

In [24]:
# add column for number of classified reads per sample
import re
slurmdir='/work/pi_sarah_gignouxwolfsohn_uml_edu/nikea/COL/slurms/slurm-bracken-filtering-S-60079718.out'
#make sure the order in which kraken.outs are merged are in the same order as the samplelist

In [ ]:
#This is the pattern in the slurm output I want to pull read #s from
# 242006 reads remaining (213219 reads excluded)

In [25]:
# Read the output report and extract the total number of reads
with open(slurmdir, 'r') as file:
    report_text = file.read()

In [26]:
# Extract total number of reads using regular expression
total_reads_pattern = re.compile(r'(\d+) reads remaining')
total_reads_matches = total_reads_pattern.findall(report_text)
total_reads_matches

['124063',
 '328559',
 '102388',
 '154743',
 '128336',
 '298188',
 '379767',
 '349188',
 '333390',
 '278457',
 '291083',
 '204900',
 '132502',
 '154296',
 '60893',
 '151132',
 '182696',
 '96102',
 '101278',
 '276882',
 '145986',
 '157477',
 '199662',
 '154445',
 '190733',
 '184051',
 '170405',
 '221635',
 '173186',
 '182924',
 '214274',
 '249607',
 '239867',
 '237562',
 '256702',
 '690698',
 '581037',
 '954821',
 '196977',
 '383793',
 '320226',
 '771194',
 '631142',
 '199423',
 '280036',
 '368781',
 '906268',
 '264172',
 '571865',
 '643089',
 '548604',
 '598090',
 '577368',
 '703989',
 '872976',
 '543931']

In [27]:
# Create a dictionary to map sample ID to total reads
total_reads_dict = {samplelist[i]: int(total_reads_matches[i]) for i in range(len(samplelist))}

# Display the updated DataFrame
print(total_reads_dict)

{'032024_COL_SAN_T5_139_OFAV_S17': 124063, '032024_COL_SAN_T5_140_OFAV_S18c': 328559, '032024_COL_SAN_T5_141_OFAV_S19': 102388, '032024_COL_SAN_T5_166_OFAV_S20': 154743, '032024_COL_SAN_T5_167_OFAV_S21': 128336, '012025_COL_SAN_T5_568_OFAV_S1': 298188, '012025_COL_SAN_T5_572_OFAV_S5': 379767, '012025_COL_SAN_T5_580_OFAV_S13': 349188, '012025_COL_SAN_T5_584_OFAV_S17': 333390, '012025_COL_SAN_T5_585_OFAV_S18': 278457, '012025_COL_SAN_T5_596_OFAV_S29': 291083, '032024_COL_SAN_T5_128_MCAV_S1': 204900, '032024_COL_SAN_T5_129_MCAV_S2': 132502, '032024_COL_SAN_T5_130_MCAV_S37': 154296, '032024_COL_SAN_T5_131_MCAV_S3': 60893, '032024_COL_SAN_T5_132_MCAV_S4': 151132, '032024_COL_SAN_T5_133_MCAV_S5': 182696, '032024_COL_SAN_T5_134_MCAV_S6': 96102, '032024_COL_SAN_T5_136_MCAV_S7': 101278, '032024_COL_SAN_T5_150_MCAV_S8': 276882, '012025_COL_SAN_T5_574_MCAV_S7': 145986, '012025_COL_SAN_T5_578_MCAV_S11': 157477, '012025_COL_SAN_T5_581_MCAV_S14': 199662, '012025_COL_SAN_T5_583_MCAV_S16': 154445, '012025_COL_SAN_T5_588_MCAV_S21': 190733, '012025_COL_SAN_T5_589_MCAV_S22': 184051, '012025_COL_SAN_T5_591_MCAV_S24': 170405, '012025_COL_SAN_T5_593_MCAV_S26': 221635, '012025_COL_SAN_T5_594_MCAV_S27': 173186, '012025_COL_SAN_T5_595_MCAV_S28': 182924, '032024_COL_SAN_T5_146_DLAB_S12': 214274, '032024_COL_SAN_T5_148_DLAB_S13': 249607, '032024_COL_SAN_T5_149_DLAB_S14': 239867, '032024_COL_SAN_T5_158_DLAB_S15': 237562, '032024_COL_SAN_T5_159_DLAB_S16': 256702, '032024_COL_SAN_T5_143_DLAB_S40': 690698, '032024_COL_SAN_T5_160_DLAB_S41': 581037, '032024_COL_SAN_T5_161_DLAB_S42': 954821, '012025_COL_SAN_T5_569_DLAB_S2': 196977, '012025_COL_SAN_T5_570_DLAB_S3': 383793, '012025_COL_SAN_T5_571_DLAB_S4': 320226, '012025_COL_SAN_T5_575_DLAB_S8': 771194, '012025_COL_SAN_T5_579_DLAB_S12': 631142, '012025_COL_SAN_T5_586_DLAB_S19': 199423, '032024_COL_SAN_T5_144_PSTR_S9': 280036, '032024_COL_SAN_T5_147_PSTR_S10': 368781, '032024_COL_SAN_T5_163_PSTR_S11c': 906268, '032024_COL_SAN_T5_154_PSTR_S38': 264172, '032024_COL_SAN_T5_162_PSTR_S39': 571865, '012025_COL_SAN_T5_573_PSTR_S6': 643089, '012025_COL_SAN_T5_576_PSTR_S9': 548604, '012025_COL_SAN_T5_577_PSTR_S10': 598090, '012025_COL_SAN_T5_582_PSTR_S15': 577368, '012025_COL_SAN_T5_587_PSTR_S20': 703989, '012025_COL_SAN_T5_590_PSTR_S23': 872976, '012025_COL_SAN_T5_592_PSTR_S25': 543931}

In [29]:
# Convert main df to raw abundances 
normalized_otus=otu_table.loc[:,otu_table.columns.str.contains("num")]
#headers in the otu table need to match the all_sampleids.txt
normalized_otus.columns = normalized_otus.columns.str.replace('_S_filt.bracken_num', '')
normalized_otus

,012025_COL_SAN_T5_568_OFAV_S1,012025_COL_SAN_T5_569_DLAB_S2,012025_COL_SAN_T5_570_DLAB_S3,012025_COL_SAN_T5_571_DLAB_S4,012025_COL_SAN_T5_572_OFAV_S5,012025_COL_SAN_T5_573_PSTR_S6,012025_COL_SAN_T5_574_MCAV_S7,012025_COL_SAN_T5_575_DLAB_S8,012025_COL_SAN_T5_576_PSTR_S9,012025_COL_SAN_T5_577_PSTR_S10,...,032024_COL_SAN_T5_150_MCAV_S8,032024_COL_SAN_T5_154_PSTR_S38,032024_COL_SAN_T5_158_DLAB_S15,032024_COL_SAN_T5_159_DLAB_S16,032024_COL_SAN_T5_160_DLAB_S41,032024_COL_SAN_T5_161_DLAB_S42,032024_COL_SAN_T5_162_PSTR_S39,032024_COL_SAN_T5_163_PSTR_S11c,032024_COL_SAN_T5_166_OFAV_S20,032024_COL_SAN_T5_167_OFAV_S21
taxonomy_id,,,,,,,,,,,,,,,,,,,,,
562,8767,1165,9657,20235,11316,2504,503,4986,2167,2270,...,1604,1961,1500,1640,3807,13813,2475,3867,5016,3735
28213,4039,42,206,198,3934,217,2639,3734,20,40,...,22,0,0,0,0,98,0,3322,0,0
573,1918,912,841,1035,1478,1249,610,4455,1247,1976,...,3859,519,682,594,1157,2405,1289,2891,1497,902
2721244,1700,224,68,283,2667,221,0,311,209,238,...,105,214,240,299,452,201,213,324,1000,917
238834,1618,141,234,158,2031,500,166,175,642,774,...,155,235,296,301,617,784,569,1098,716,743
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3432288,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,12,0,0
3066159,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,11,0,0
3139326,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,11,0,0
2846609,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,10,0
2976884,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,17

In [30]:
# Convert the dictionary to a DataFrame and transpose it
sample_counts_df = pd.DataFrame(total_reads_dict, index=['Total_reads'])
sample_counts_df

,032024_COL_SAN_T5_139_OFAV_S17,032024_COL_SAN_T5_140_OFAV_S18c,032024_COL_SAN_T5_141_OFAV_S19,032024_COL_SAN_T5_166_OFAV_S20,032024_COL_SAN_T5_167_OFAV_S21,012025_COL_SAN_T5_568_OFAV_S1,012025_COL_SAN_T5_572_OFAV_S5,012025_COL_SAN_T5_580_OFAV_S13,012025_COL_SAN_T5_584_OFAV_S17,012025_COL_SAN_T5_585_OFAV_S18,...,032024_COL_SAN_T5_163_PSTR_S11c,032024_COL_SAN_T5_154_PSTR_S38,032024_COL_SAN_T5_162_PSTR_S39,012025_COL_SAN_T5_573_PSTR_S6,012025_COL_SAN_T5_576_PSTR_S9,012025_COL_SAN_T5_577_PSTR_S10,012025_COL_SAN_T5_582_PSTR_S15,012025_COL_SAN_T5_587_PSTR_S20,012025_COL_SAN_T5_590_PSTR_S23,012025_COL_SAN_T5_592_PSTR_S25
Total_reads,124063,328559,102388,154743,128336,298188,379767,349188,333390,278457,...,906268,264172,571865,643089,548604,598090,577368,703989,872976,543931

In [31]:
# Concatenate the original DataFrame and the new DataFrame with the total reads row
normalized_otus = pd.concat([normalized_otus, sample_counts_df],axis=0)
normalized_otus

,012025_COL_SAN_T5_568_OFAV_S1,012025_COL_SAN_T5_569_DLAB_S2,012025_COL_SAN_T5_570_DLAB_S3,012025_COL_SAN_T5_571_DLAB_S4,012025_COL_SAN_T5_572_OFAV_S5,012025_COL_SAN_T5_573_PSTR_S6,012025_COL_SAN_T5_574_MCAV_S7,012025_COL_SAN_T5_575_DLAB_S8,012025_COL_SAN_T5_576_PSTR_S9,012025_COL_SAN_T5_577_PSTR_S10,...,032024_COL_SAN_T5_150_MCAV_S8,032024_COL_SAN_T5_154_PSTR_S38,032024_COL_SAN_T5_158_DLAB_S15,032024_COL_SAN_T5_159_DLAB_S16,032024_COL_SAN_T5_160_DLAB_S41,032024_COL_SAN_T5_161_DLAB_S42,032024_COL_SAN_T5_162_PSTR_S39,032024_COL_SAN_T5_163_PSTR_S11c,032024_COL_SAN_T5_166_OFAV_S20,032024_COL_SAN_T5_167_OFAV_S21
562,8767,1165,9657,20235,11316,2504,503,4986,2167,2270,...,1604,1961,1500,1640,3807,13813,2475,3867,5016,3735
28213,4039,42,206,198,3934,217,2639,3734,20,40,...,22,0,0,0,0,98,0,3322,0,0
573,1918,912,841,1035,1478,1249,610,4455,1247,1976,...,3859,519,682,594,1157,2405,1289,2891,1497,902
2721244,1700,224,68,283,2667,221,0,311,209,238,...,105,214,240,299,452,201,213,324,1000,917
238834,1618,141,234,158,2031,500,166,175,642,774,...,155,235,296,301,617,784,569,1098,716,743
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3066159,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,11,0,0
3139326,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,11,0,0
2846609,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,10,0
2976884,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,17
Total_reads,298188,196977,383793,320226,379767,643089,145986,771194,548604,598090,...,276882,264172,237562,256702,581037,954821,571865,906268,154743,128336

In [32]:
# Normalize: divide reads by total reads and multiply by 1 million
normalized_otu = (normalized_otus / normalized_otus.loc['Total_reads'] * 1E6)
# replace total reads row again 
normalized_otu.loc['Total_reads',:]=normalized_otus.loc['Total_reads',:]
normalized_otu["Sum"]=normalized_otu.sum(axis=1)
normalized_otu.sort_values(by="Sum", ascending=False)

,012025_COL_SAN_T5_568_OFAV_S1,012025_COL_SAN_T5_569_DLAB_S2,012025_COL_SAN_T5_570_DLAB_S3,012025_COL_SAN_T5_571_DLAB_S4,012025_COL_SAN_T5_572_OFAV_S5,012025_COL_SAN_T5_573_PSTR_S6,012025_COL_SAN_T5_574_MCAV_S7,012025_COL_SAN_T5_575_DLAB_S8,012025_COL_SAN_T5_576_PSTR_S9,012025_COL_SAN_T5_577_PSTR_S10,...,032024_COL_SAN_T5_154_PSTR_S38,032024_COL_SAN_T5_158_DLAB_S15,032024_COL_SAN_T5_159_DLAB_S16,032024_COL_SAN_T5_160_DLAB_S41,032024_COL_SAN_T5_161_DLAB_S42,032024_COL_SAN_T5_162_PSTR_S39,032024_COL_SAN_T5_163_PSTR_S11c,032024_COL_SAN_T5_166_OFAV_S20,032024_COL_SAN_T5_167_OFAV_S21,Sum
Total_reads,298188.000000,196977.000000,383793.000000,320226.000000,379767.000000,643089.000000,145986.000000,771194.000000,548604.000000,598090.000000,...,264172.000000,237562.000000,256702.000000,581037.000000,954821.000000,571865.000000,906268.000000,154743.000000,128336.000000,1.871584e+07
562,29400.914859,5914.396097,25162.001391,63189.747241,29797.217768,3893.706781,3445.535873,6465.299263,3950.025884,3795.415406,...,7423.193980,6314.141151,6388.730902,6552.078439,14466.585884,4327.944532,4266.949732,32415.036544,29103.291360,7.121588e+05
1173583,57.011013,0.000000,28.661284,0.000000,76.362612,7409.549845,0.000000,22.043740,85143.382112,36011.302647,...,7805.520646,101.026258,151.927137,58.516067,65.980953,8147.027708,84391.151403,77.547934,116.880688,4.209103e+05
2057741,2796.893235,436.599197,1292.363331,412.208877,2196.083388,905.006928,3897.634020,1680.511000,107.545698,187.262787,...,47041.321563,4095.772893,2746.375174,31741.524206,16684.802701,81813.015310,2662.567806,2785.263308,3194.738811,4.178326e+05
28213,13545.146015,213.222864,536.747674,618.313316,10358.983271,337.433854,18077.075884,4841.842649,36.456169,66.879567,...,0.000000,0.000000,0.000000,0.000000,102.637039,0.000000,3665.582366,0.000000,0.000000,2.806839e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2844147,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.145507e+01
2956679,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.145507e+01
3052207,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,10.473167,0.000000,0.000000,0.000000,0.000000,1.047317e+01
1987019,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,10.473167,0.000000,0.000000,0.000000,0.000000,1.047317e+01
2955750,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,10.473167,0.000000,0.000000,0.000000,0.000000,1.047317e+01

In [33]:
# export otu table to csv
normalized_otu.to_csv("otu_normtable_species.csv")

This otu table still has Total_reads row and Sum column. These should be removed and add taxonomy_id label to the first column

**this notebook stops here, below is code from DR analysis in case I want to do this with COL data, delete if I decide not to**

### Now let's do Kindgom level

starting at step 7: reading in the phylum otu table this time

In [48]:
otu_table_k=pd.read_csv("/scratch4/workspace/nikea_ulrich_uml_edu-col_data/kraken2_pluspf/bracken_ready/all_merged_bracken_K.txt", sep='\t')

In [49]:
otu_table_k.set_index("taxonomy_id",inplace=True)

In [50]:
otu_table_k.head()

,name,taxonomy_lvl,012025_COL_SAN_T5_568_OFAV_S1_K_filt.bracken_num,012025_COL_SAN_T5_568_OFAV_S1_K_filt.bracken_frac,012025_COL_SAN_T5_569_DLAB_S2_K_filt.bracken_num,012025_COL_SAN_T5_569_DLAB_S2_K_filt.bracken_frac,012025_COL_SAN_T5_570_DLAB_S3_K_filt.bracken_num,012025_COL_SAN_T5_570_DLAB_S3_K_filt.bracken_frac,012025_COL_SAN_T5_571_DLAB_S4_K_filt.bracken_num,012025_COL_SAN_T5_571_DLAB_S4_K_filt.bracken_frac,...,032024_COL_SAN_T5_161_DLAB_S42_K_filt.bracken_num,032024_COL_SAN_T5_161_DLAB_S42_K_filt.bracken_frac,032024_COL_SAN_T5_162_PSTR_S39_K_filt.bracken_num,032024_COL_SAN_T5_162_PSTR_S39_K_filt.bracken_frac,032024_COL_SAN_T5_163_PSTR_S11c_K_filt.bracken_num,032024_COL_SAN_T5_163_PSTR_S11c_K_filt.bracken_frac,032024_COL_SAN_T5_166_OFAV_S20_K_filt.bracken_num,032024_COL_SAN_T5_166_OFAV_S20_K_filt.bracken_frac,032024_COL_SAN_T5_167_OFAV_S21_K_filt.bracken_num,032024_COL_SAN_T5_167_OFAV_S21_K_filt.bracken_frac
taxonomy_id,,,,,,,,,,,,,,,,,,,,,
3379134,Pseudomonadati,K,181298,0.57168,137696,0.59928,287851,0.69659,236746,0.67160,...,651754,0.66656,394104,0.65994,540899,0.58262,106330,0.59105,82693,0.55805
1783272,Bacillati,K,106848,0.33692,73899,0.32162,105088,0.25431,100175,0.28417,...,268524,0.27463,165160,0.27657,304046,0.32750,58288,0.32400,51651,0.34857
4751,Fungi,K,15334,0.04835,7837,0.03411,10160,0.02459,7418,0.02104,...,27830,0.02846,17727,0.02968,45426,0.04893,8157,0.04534,7382,0.04982
3366610,Methanobacteriati,K,5277,0.01664,2970,0.01293,4076,0.00986,3429,0.00973,...,10761,0.01101,7450,0.01248,13452,0.01449,2697,0.01499,2343,0.01581
3384189,Fusobacteriati,K,2394,0.00755,2935,0.01277,2006,0.00485,1446,0.00410,...,5246,0.00537,3841,0.00643,7203,0.00776,1289,0.00717,1236,0.00834

In [51]:
# Make taxa otu id table 
otu_id_k=otu_table_k.iloc[:, 0:2]
otu_id_k
# export otu id 
otu_id_k.to_csv("otu_id_kingdom.csv")
#output to /bracken_filtered

In [52]:
# drop name, taxa, and frac cols
drop_columns = [col for col in otu_table_k.columns if 'frac' in col]
drop_columns.extend(['name', 'taxonomy_lvl'])
otu_table_kingdom=otu_table_k.drop(columns=drop_columns)

# rename to drop _num
#otu_table_species.columns.str.replace('_num', '')

# export otu table to csv
otu_table_kingdom.to_csv("otu_table_kingdom.csv")

In [53]:
# add column for number of classified reads per sample
import re
slurmdir_k='/work/pi_sarah_gignouxwolfsohn_uml_edu/nikea/COL/slurms/slurm-bracken-filtering-K-60079719.out'
#make sure the order in which kraken.outs are merged are in the same order as the samplelist

In [54]:
# Read the output report and extract the total number of reads
with open(slurmdir_k, 'r') as file:
    report_text = file.read()

In [55]:
# Extract total number of reads using regular expression
total_reads_pattern = re.compile(r'(\d+) reads remaining')
total_reads_matches = total_reads_pattern.findall(report_text)
total_reads_matches

['143624',
 '346718',
 '122420',
 '179900',
 '148181',
 '317133',
 '401581',
 '369887',
 '350040',
 '297284',
 '310327',
 '229236',
 '160525',
 '183511',
 '82817',
 '172275',
 '205885',
 '117749',
 '123178',
 '305906',
 '164551',
 '183897',
 '218683',
 '173285',
 '218070',
 '203907',
 '196532',
 '248173',
 '191357',
 '206118',
 '238971',
 '276493',
 '263914',
 '261633',
 '280987',
 '712364',
 '606889',
 '977783',
 '229770',
 '413230',
 '352513',
 '793449',
 '657342',
 '229512',
 '301637',
 '396191',
 '928398',
 '291301',
 '597183',
 '666162',
 '570124',
 '622142',
 '600661',
 '723692',
 '893775',
 '567231']

In [56]:
# Create a dictionary to map sample ID to total reads
total_reads_dict = {samplelist[i]: int(total_reads_matches[i]) for i in range(len(samplelist))}

# Display the updated DataFrame
print(total_reads_dict)

{'032024_COL_SAN_T5_139_OFAV_S17': 143624, '032024_COL_SAN_T5_140_OFAV_S18c': 346718, '032024_COL_SAN_T5_141_OFAV_S19': 122420, '032024_COL_SAN_T5_166_OFAV_S20': 179900, '032024_COL_SAN_T5_167_OFAV_S21': 148181, '012025_COL_SAN_T5_568_OFAV_S1': 317133, '012025_COL_SAN_T5_572_OFAV_S5': 401581, '012025_COL_SAN_T5_580_OFAV_S13': 369887, '012025_COL_SAN_T5_584_OFAV_S17': 350040, '012025_COL_SAN_T5_585_OFAV_S18': 297284, '012025_COL_SAN_T5_596_OFAV_S29': 310327, '032024_COL_SAN_T5_128_MCAV_S1': 229236, '032024_COL_SAN_T5_129_MCAV_S2': 160525, '032024_COL_SAN_T5_130_MCAV_S37': 183511, '032024_COL_SAN_T5_131_MCAV_S3': 82817, '032024_COL_SAN_T5_132_MCAV_S4': 172275, '032024_COL_SAN_T5_133_MCAV_S5': 205885, '032024_COL_SAN_T5_134_MCAV_S6': 117749, '032024_COL_SAN_T5_136_MCAV_S7': 123178, '032024_COL_SAN_T5_150_MCAV_S8': 305906, '012025_COL_SAN_T5_574_MCAV_S7': 164551, '012025_COL_SAN_T5_578_MCAV_S11': 183897, '012025_COL_SAN_T5_581_MCAV_S14': 218683, '012025_COL_SAN_T5_583_MCAV_S16': 173285, '012025_COL_SAN_T5_588_MCAV_S21': 218070, '012025_COL_SAN_T5_589_MCAV_S22': 203907, '012025_COL_SAN_T5_591_MCAV_S24': 196532, '012025_COL_SAN_T5_593_MCAV_S26': 248173, '012025_COL_SAN_T5_594_MCAV_S27': 191357, '012025_COL_SAN_T5_595_MCAV_S28': 206118, '032024_COL_SAN_T5_146_DLAB_S12': 238971, '032024_COL_SAN_T5_148_DLAB_S13': 276493, '032024_COL_SAN_T5_149_DLAB_S14': 263914, '032024_COL_SAN_T5_158_DLAB_S15': 261633, '032024_COL_SAN_T5_159_DLAB_S16': 280987, '032024_COL_SAN_T5_143_DLAB_S40': 712364, '032024_COL_SAN_T5_160_DLAB_S41': 606889, '032024_COL_SAN_T5_161_DLAB_S42': 977783, '012025_COL_SAN_T5_569_DLAB_S2': 229770, '012025_COL_SAN_T5_570_DLAB_S3': 413230, '012025_COL_SAN_T5_571_DLAB_S4': 352513, '012025_COL_SAN_T5_575_DLAB_S8': 793449, '012025_COL_SAN_T5_579_DLAB_S12': 657342, '012025_COL_SAN_T5_586_DLAB_S19': 229512, '032024_COL_SAN_T5_144_PSTR_S9': 301637, '032024_COL_SAN_T5_147_PSTR_S10': 396191, '032024_COL_SAN_T5_163_PSTR_S11c': 928398, '032024_COL_SAN_T5_154_PSTR_S38': 291301, '032024_COL_SAN_T5_162_PSTR_S39': 597183, '012025_COL_SAN_T5_573_PSTR_S6': 666162, '012025_COL_SAN_T5_576_PSTR_S9': 570124, '012025_COL_SAN_T5_577_PSTR_S10': 622142, '012025_COL_SAN_T5_582_PSTR_S15': 600661, '012025_COL_SAN_T5_587_PSTR_S20': 723692, '012025_COL_SAN_T5_590_PSTR_S23': 893775, '012025_COL_SAN_T5_592_PSTR_S25': 567231}

In [57]:
# Convert main df to raw abundances 
normalized_otus_k=otu_table_k.loc[:,otu_table_k.columns.str.contains("num")]
#headers in the otu table need to match the all_sampleids.txt
normalized_otus_k.columns = normalized_otus_k.columns.str.replace('_K_filt.bracken_num', '')
normalized_otus_k

,012025_COL_SAN_T5_568_OFAV_S1,012025_COL_SAN_T5_569_DLAB_S2,012025_COL_SAN_T5_570_DLAB_S3,012025_COL_SAN_T5_571_DLAB_S4,012025_COL_SAN_T5_572_OFAV_S5,012025_COL_SAN_T5_573_PSTR_S6,012025_COL_SAN_T5_574_MCAV_S7,012025_COL_SAN_T5_575_DLAB_S8,012025_COL_SAN_T5_576_PSTR_S9,012025_COL_SAN_T5_577_PSTR_S10,...,032024_COL_SAN_T5_150_MCAV_S8,032024_COL_SAN_T5_154_PSTR_S38,032024_COL_SAN_T5_158_DLAB_S15,032024_COL_SAN_T5_159_DLAB_S16,032024_COL_SAN_T5_160_DLAB_S41,032024_COL_SAN_T5_161_DLAB_S42,032024_COL_SAN_T5_162_PSTR_S39,032024_COL_SAN_T5_163_PSTR_S11c,032024_COL_SAN_T5_166_OFAV_S20,032024_COL_SAN_T5_167_OFAV_S21
taxonomy_id,,,,,,,,,,,,,,,,,,,,,
3379134,181298,137696,287851,236746,228372,447875,90293,536444,331618,345716,...,210553,181442,142885,148759,357445,651754,394104,540899,106330,82693
1783272,106848,73899,105088,100175,135624,179964,58050,230357,188750,215834,...,81511,89602,93166,102926,200415,268524,165160,304046,58288,51651
4751,15334,7837,10160,7418,20027,19010,8757,11402,26170,33073,...,6257,9504,12916,14971,20833,27830,17727,45426,8157,7382
3366610,5277,2970,4076,3429,6779,7493,2347,7572,8374,9537,...,2856,4435,4696,4279,7400,10761,7450,13452,2697,2343
3384189,2394,2935,2006,1446,2847,3477,1419,1876,4455,5200,...,1588,1608,2471,3160,5632,5246,3841,7203,1289,1236
1783275,1942,2542,1144,733,2500,2971,1217,1153,3311,5168,...,774,1307,1718,2534,4758,4745,2974,5416,846,904
2731360,1292,550,1207,899,1786,2105,545,1085,2399,2405,...,499,1409,1317,1524,2847,3138,1966,3838,717,668
3384194,1101,758,1016,941,1819,1839,803,2621,2422,2640,...,1030,986,1208,1239,5288,3042,2371,4020,761,588
2732005,1071,292,350,389,936,610,535,606,1110,1215,...,378,381,764,799,1088,1248,704,1623,450,463
2732396,272,152,152,101,362,371,221,123,636,565,...,146,248,311,250,424,537,391,1057,170,128
1935183,212,22,24,19,392,63,63,51,222,171,...,81,51,125,130,173,201,94,329,123,100
2840023,38,23,0,18,25,0,58,18,0,0,...,28,0,0,10,0,0,0,0,0,0
2732092,28,0,0,0,70,46,47,0,89,62,...,18,51,20,33,47,78,74,150,36,13
1783276,26,0,18,11,42,42,22,29,68,60,...,25,25,36,37,57,86,29,119,36,12
2732397,0,94,138,188,0,296,174,112,500,496,...,162,252,0,336,482,593,298,820,0,0
2732091,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [58]:
# Convert the dictionary to a DataFrame and transpose it
sample_counts_df_k = pd.DataFrame(total_reads_dict, index=['Total_reads'])
sample_counts_df_k

,032024_COL_SAN_T5_139_OFAV_S17,032024_COL_SAN_T5_140_OFAV_S18c,032024_COL_SAN_T5_141_OFAV_S19,032024_COL_SAN_T5_166_OFAV_S20,032024_COL_SAN_T5_167_OFAV_S21,012025_COL_SAN_T5_568_OFAV_S1,012025_COL_SAN_T5_572_OFAV_S5,012025_COL_SAN_T5_580_OFAV_S13,012025_COL_SAN_T5_584_OFAV_S17,012025_COL_SAN_T5_585_OFAV_S18,...,032024_COL_SAN_T5_163_PSTR_S11c,032024_COL_SAN_T5_154_PSTR_S38,032024_COL_SAN_T5_162_PSTR_S39,012025_COL_SAN_T5_573_PSTR_S6,012025_COL_SAN_T5_576_PSTR_S9,012025_COL_SAN_T5_577_PSTR_S10,012025_COL_SAN_T5_582_PSTR_S15,012025_COL_SAN_T5_587_PSTR_S20,012025_COL_SAN_T5_590_PSTR_S23,012025_COL_SAN_T5_592_PSTR_S25
Total_reads,143624,346718,122420,179900,148181,317133,401581,369887,350040,297284,...,928398,291301,597183,666162,570124,622142,600661,723692,893775,567231

In [59]:
# Concatenate the original DataFrame and the new DataFrame with the total reads row
normalized_otus_k = pd.concat([normalized_otus_k, sample_counts_df_k],axis=0)
normalized_otus_k

,012025_COL_SAN_T5_568_OFAV_S1,012025_COL_SAN_T5_569_DLAB_S2,012025_COL_SAN_T5_570_DLAB_S3,012025_COL_SAN_T5_571_DLAB_S4,012025_COL_SAN_T5_572_OFAV_S5,012025_COL_SAN_T5_573_PSTR_S6,012025_COL_SAN_T5_574_MCAV_S7,012025_COL_SAN_T5_575_DLAB_S8,012025_COL_SAN_T5_576_PSTR_S9,012025_COL_SAN_T5_577_PSTR_S10,...,032024_COL_SAN_T5_150_MCAV_S8,032024_COL_SAN_T5_154_PSTR_S38,032024_COL_SAN_T5_158_DLAB_S15,032024_COL_SAN_T5_159_DLAB_S16,032024_COL_SAN_T5_160_DLAB_S41,032024_COL_SAN_T5_161_DLAB_S42,032024_COL_SAN_T5_162_PSTR_S39,032024_COL_SAN_T5_163_PSTR_S11c,032024_COL_SAN_T5_166_OFAV_S20,032024_COL_SAN_T5_167_OFAV_S21
3379134,181298,137696,287851,236746,228372,447875,90293,536444,331618,345716,...,210553,181442,142885,148759,357445,651754,394104,540899,106330,82693
1783272,106848,73899,105088,100175,135624,179964,58050,230357,188750,215834,...,81511,89602,93166,102926,200415,268524,165160,304046,58288,51651
4751,15334,7837,10160,7418,20027,19010,8757,11402,26170,33073,...,6257,9504,12916,14971,20833,27830,17727,45426,8157,7382
3366610,5277,2970,4076,3429,6779,7493,2347,7572,8374,9537,...,2856,4435,4696,4279,7400,10761,7450,13452,2697,2343
3384189,2394,2935,2006,1446,2847,3477,1419,1876,4455,5200,...,1588,1608,2471,3160,5632,5246,3841,7203,1289,1236
1783275,1942,2542,1144,733,2500,2971,1217,1153,3311,5168,...,774,1307,1718,2534,4758,4745,2974,5416,846,904
2731360,1292,550,1207,899,1786,2105,545,1085,2399,2405,...,499,1409,1317,1524,2847,3138,1966,3838,717,668
3384194,1101,758,1016,941,1819,1839,803,2621,2422,2640,...,1030,986,1208,1239,5288,3042,2371,4020,761,588
2732005,1071,292,350,389,936,610,535,606,1110,1215,...,378,381,764,799,1088,1248,704,1623,450,463
2732396,272,152,152,101,362,371,221,123,636,565,...,146,248,311,250,424,537,391,1057,170,128
1935183,212,22,24,19,392,63,63,51,222,171,...,81,51,125,130,173,201,94,329,123,100
2840023,38,23,0,18,25,0,58,18,0,0,...,28,0,0,10,0,0,0,0,0,0
2732092,28,0,0,0,70,46,47,0,89,62,...,18,51,20,33,47,78,74,150,36,13
1783276,26,0,18,11,42,42,22,29,68,60,...,25,25,36,37,57,86,29,119,36,12
2732397,0,94,138,188,0,296,174,112,500,496,...,162,252,0,336,482,593,298,820,0,0
2732091,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Total_reads,317133,229770,413230,352513,401581,666162,164551,793449,570124,622142,...,305906,291301,261633,280987,606889,977783,597183,928398,179900,148181

something weird is happening. Total reads should have the most in each sample, not a taxID. Ok it is doing the math correctly but then not replacing the total reads row with new sum. That's ok, will be removing the total reads column anyway

In [60]:
# Normalize: divide reads by total reads and multiply by 1 million
normalized_otu_k = (normalized_otus_k / normalized_otus_k.loc['Total_reads'] * 1E6)
# replace total reads row again 
normalized_otu_k.loc['Total_reads',:]=normalized_otus_k.loc['Total_reads',:]
normalized_otu_k["Sum"]=normalized_otu_k.sum(axis=1)
normalized_otu_k.sort_values(by="Sum", ascending=False)

,012025_COL_SAN_T5_568_OFAV_S1,012025_COL_SAN_T5_569_DLAB_S2,012025_COL_SAN_T5_570_DLAB_S3,012025_COL_SAN_T5_571_DLAB_S4,012025_COL_SAN_T5_572_OFAV_S5,012025_COL_SAN_T5_573_PSTR_S6,012025_COL_SAN_T5_574_MCAV_S7,012025_COL_SAN_T5_575_DLAB_S8,012025_COL_SAN_T5_576_PSTR_S9,012025_COL_SAN_T5_577_PSTR_S10,...,032024_COL_SAN_T5_154_PSTR_S38,032024_COL_SAN_T5_158_DLAB_S15,032024_COL_SAN_T5_159_DLAB_S16,032024_COL_SAN_T5_160_DLAB_S41,032024_COL_SAN_T5_161_DLAB_S42,032024_COL_SAN_T5_162_PSTR_S39,032024_COL_SAN_T5_163_PSTR_S11c,032024_COL_SAN_T5_166_OFAV_S20,032024_COL_SAN_T5_167_OFAV_S21,Sum
3379134,571678.128735,599277.538408,696587.856642,671595.090110,568682.283275,672321.447336,548723.496059,676091.342985,581659.428475,555686.643885,...,622867.755346,546127.590938,529415.951628,588979.203775,666563.030857,659938.410839,582615.430020,591050.583658,558054.001525,3.209723e+07
Total_reads,317133.000000,229770.000000,413230.000000,352513.000000,401581.000000,666162.000000,164551.000000,793449.000000,570124.000000,622142.000000,...,291301.000000,261633.000000,280987.000000,606889.000000,977783.000000,597183.000000,928398.000000,179900.000000,148181.000000,2.002610e+07
1783272,336918.579902,321621.621622,254308.738475,284173.916990,337725.141379,270150.503931,352778.166040,290323.637688,331068.328995,346920.799432,...,307592.490242,356094.223588,366301.643848,330233.370518,274625.351433,276565.139999,327495.319895,324002.223457,348566.955278,1.922301e+07
4751,48351.953281,34108.021065,24586.791859,21043.195570,49870.387294,28536.602208,53217.543497,14370.173760,45902.294939,53159.889543,...,32626.046598,49366.861214,53280.044984,34327.529416,28462.347985,29684.368108,48929.446207,45341.856587,49817.452980,2.385044e+06
3366610,16639.706369,12925.969448,9863.756262,9727.300837,16880.778722,11248.014747,14263.055223,9543.146440,14688.032779,15329.297813,...,15224.801837,17948.806152,15228.462527,12193.333542,11005.509402,12475.237909,14489.475419,14991.662034,15811.743746,8.171948e+05
3384189,7548.883276,12773.643208,4854.439416,4101.976381,7089.478835,5219.451125,8623.466281,2364.361162,7814.089566,8358.220471,...,5520.063440,9444.527258,11246.071882,9280.115474,5365.198618,6431.864269,7758.525977,7165.091718,8341.150350,4.629100e+05
1783275,6123.613752,11063.237150,2768.434044,2079.355939,6225.394130,4459.876126,7395.883343,1453.149478,5807.508542,8306.785268,...,4486.767982,6566.449951,9018.210807,7839.983918,4852.814991,4980.047992,5833.704941,4702.612563,6100.647181,3.144244e+05
3384194,3471.729527,3298.951125,2458.679186,2669.405100,4529.596769,2760.589766,4879.946035,3303.299897,4248.198637,4243.404239,...,3384.815020,4617.154564,4409.456665,8713.290239,3111.119747,3970.307259,4330.039487,4230.127849,3968.120069,2.296948e+05
2731360,4074.000498,2393.698046,2920.891513,2550.260558,4447.421566,3159.892038,3312.043075,1367.447687,4207.856536,3865.676968,...,4836.921260,5033.768676,5423.738465,4691.137918,3209.301041,3292.123185,4134.002874,3985.547526,4508.000351,2.090173e+05
2732005,3377.131992,1270.836053,846.985940,1103.505403,2330.787562,915.693180,3251.271642,763.754192,1946.944875,1952.930360,...,1307.925479,2920.120933,2843.547922,1792.749580,1276.356819,1178.868119,1748.172659,2501.389661,3124.557129,1.305220e+05
2732396,857.684315,661.531096,367.833894,286.514256,901.437070,556.921590,1343.048660,155.019415,1115.546793,908.152801,...,851.353068,1188.687971,889.720877,698.645057,549.201612,654.740674,1138.520333,944.969427,863.808450,5.431094e+04
2732397,0.000000,409.104757,333.954456,533.313665,0.000000,444.336363,1057.422927,141.155890,877.002196,797.245645,...,865.084569,0.000000,1195.784858,794.214428,606.474034,499.009516,883.241885,0.000000,0.000000,3.524158e+04
1935183,668.489246,95.747922,58.079036,53.898721,976.141800,94.571591,382.860025,64.276343,389.388975,274.856865,...,175.076639,477.768477,462.654856,285.060365,205.567084,157.405686,354.373878,683.713174,674.850352,2.239669e+04
2732092,88.291032,0.000000,0.000000,0.000000,174.311036,69.052273,285.625733,0.000000,156.106391,99.655706,...,175.076639,76.442956,117.443156,77.444145,79.772301,123.915115,161.568638,200.111173,87.730546,9.052713e+03
1783276,81.984530,0.000000,43.559277,31.204523,104.586621,63.047727,133.697152,36.549293,119.272299,96.441005,...,85.821882,137.597321,131.678690,93.921623,87.954076,48.561329,128.177786,200.111173,80.982042,6.397440e+03
2840023,119.823544,100.100100,0.000000,51.061947,62.253941,0.000000,352.474309,22.685768,0.000000,0.000000,...,0.000000,0.000000,35.588835,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.534611e+03
2732091,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.796344e+01

In [61]:
# export otu table to csv
normalized_otu_k.to_csv("otu_normtable_kingdom.csv")