### Converting bracken output to normalized ASV table

#### let's start with species level

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [4]:
import os

In [5]:
os.chdir('/work/pi_sarah_gignouxwolfsohn_uml_edu/nikea/COL')

In [6]:
os.chdir('/scratch4/workspace/nikea_ulrich_uml_edu-col_data/kraken2_pluspf/bracken_filtered')

In [26]:
# Set path variables and create sample list 
SAMPLES='/work/pi_sarah_gignouxwolfsohn_uml_edu/nikea/COL/all_sampleids.txt'
BRACKENS='/scratch4/workspace/nikea_ulrich_uml_edu-col_data/kraken2_pluspf/bracken_filtered'
samplelist=[]

with open(SAMPLES) as samples:
    for line in samples:
        samplelist.append(line.strip())
print(samplelist)

sample_names_string = ','.join(samplelist)
print(sample_names_string)
print(len(samplelist))

['012025_COL_SAN_T5_568_OFAV_S1', '012025_COL_SAN_T5_569_DLAB_S2', '012025_COL_SAN_T5_570_DLAB_S3', '012025_COL_SAN_T5_571_DLAB_S4', '012025_COL_SAN_T5_572_OFAV_S5', '012025_COL_SAN_T5_573_PSTR_S6', '012025_COL_SAN_T5_574_MCAV_S7', '012025_COL_SAN_T5_575_DLAB_S8', '012025_COL_SAN_T5_576_PSTR_S9', '012025_COL_SAN_T5_577_PSTR_S10', '012025_COL_SAN_T5_578_MCAV_S11', '012025_COL_SAN_T5_579_DLAB_S12', '012025_COL_SAN_T5_580_OFAV_S13', '012025_COL_SAN_T5_581_MCAV_S14', '012025_COL_SAN_T5_582_PSTR_S15', '012025_COL_SAN_T5_583_MCAV_S16', '012025_COL_SAN_T5_584_OFAV_S17', '012025_COL_SAN_T5_585_OFAV_S18', '012025_COL_SAN_T5_586_DLAB_S19', '012025_COL_SAN_T5_587_PSTR_S20', '012025_COL_SAN_T5_588_MCAV_S21', '012025_COL_SAN_T5_589_MCAV_S22', '012025_COL_SAN_T5_590_PSTR_S23', '012025_COL_SAN_T5_591_MCAV_S24', '012025_COL_SAN_T5_592_PSTR_S25', '012025_COL_SAN_T5_593_MCAV_S26', '012025_COL_SAN_T5_594_MCAV_S27', '012025_COL_SAN_T5_595_MCAV_S28', '012025_COL_SAN_T5_596_OFAV_S29', '032024_COL_SAN_T5_128_MCAV_S1', '032024_COL_SAN_T5_129_MCAV_S2', '032024_COL_SAN_T5_130_MCAV_S37', '032024_COL_SAN_T5_131_MCAV_S3', '032024_COL_SAN_T5_132_MCAV_S4', '032024_COL_SAN_T5_133_MCAV_S5', '032024_COL_SAN_T5_134_MCAV_S6', '032024_COL_SAN_T5_136_MCAV_S7', '032024_COL_SAN_T5_139_OFAV_S17', '032024_COL_SAN_T5_140_OFAV_S18c', '032024_COL_SAN_T5_141_OFAV_S19', '032024_COL_SAN_T5_143_DLAB_S40', '032024_COL_SAN_T5_144_PSTR_S9', '032024_COL_SAN_T5_146_DLAB_S12', '032024_COL_SAN_T5_147_PSTR_S10', '032024_COL_SAN_T5_148_DLAB_S13', '032024_COL_SAN_T5_149_DLAB_S14', '032024_COL_SAN_T5_150_MCAV_S8', '032024_COL_SAN_T5_154_PSTR_S38', '032024_COL_SAN_T5_158_DLAB_S15', '032024_COL_SAN_T5_159_DLAB_S16', '032024_COL_SAN_T5_160_DLAB_S41', '032024_COL_SAN_T5_161_DLAB_S42', '032024_COL_SAN_T5_162_PSTR_S39', '032024_COL_SAN_T5_163_PSTR_S11c', '032024_COL_SAN_T5_166_OFAV_S20', '032024_COL_SAN_T5_167_OFAV_S21']
012025_COL_SAN_T5_568_OFAV_S1,012025_COL_SAN_T5_569_DLAB_S2,012025_COL_SAN_T5_570_DLAB_S3,012025_COL_SAN_T5_571_DLAB_S4,012025_COL_SAN_T5_572_OFAV_S5,012025_COL_SAN_T5_573_PSTR_S6,012025_COL_SAN_T5_574_MCAV_S7,012025_COL_SAN_T5_575_DLAB_S8,012025_COL_SAN_T5_576_PSTR_S9,012025_COL_SAN_T5_577_PSTR_S10,012025_COL_SAN_T5_578_MCAV_S11,012025_COL_SAN_T5_579_DLAB_S12,012025_COL_SAN_T5_580_OFAV_S13,012025_COL_SAN_T5_581_MCAV_S14,012025_COL_SAN_T5_582_PSTR_S15,012025_COL_SAN_T5_583_MCAV_S16,012025_COL_SAN_T5_584_OFAV_S17,012025_COL_SAN_T5_585_OFAV_S18,012025_COL_SAN_T5_586_DLAB_S19,012025_COL_SAN_T5_587_PSTR_S20,012025_COL_SAN_T5_588_MCAV_S21,012025_COL_SAN_T5_589_MCAV_S22,012025_COL_SAN_T5_590_PSTR_S23,012025_COL_SAN_T5_591_MCAV_S24,012025_COL_SAN_T5_592_PSTR_S25,012025_COL_SAN_T5_593_MCAV_S26,012025_COL_SAN_T5_594_MCAV_S27,012025_COL_SAN_T5_595_MCAV_S28,012025_COL_SAN_T5_596_OFAV_S29,032024_COL_SAN_T5_128_MCAV_S1,032024_COL_SAN_T5_129_MCAV_S2,032024_COL_SAN_T5_130_MCAV_S37,032024_COL_SAN_T5_131_MCAV_S3,032024_COL_SAN_T5_132_MCAV_S4,032024_COL_SAN_T5_133_MCAV_S5,032024_COL_SAN_T5_134_MCAV_S6,032024_COL_SAN_T5_136_MCAV_S7,032024_COL_SAN_T5_139_OFAV_S17,032024_COL_SAN_T5_140_OFAV_S18c,032024_COL_SAN_T5_141_OFAV_S19,032024_COL_SAN_T5_143_DLAB_S40,032024_COL_SAN_T5_144_PSTR_S9,032024_COL_SAN_T5_146_DLAB_S12,032024_COL_SAN_T5_147_PSTR_S10,032024_COL_SAN_T5_148_DLAB_S13,032024_COL_SAN_T5_149_DLAB_S14,032024_COL_SAN_T5_150_MCAV_S8,032024_COL_SAN_T5_154_PSTR_S38,032024_COL_SAN_T5_158_DLAB_S15,032024_COL_SAN_T5_159_DLAB_S16,032024_COL_SAN_T5_160_DLAB_S41,032024_COL_SAN_T5_161_DLAB_S42,032024_COL_SAN_T5_162_PSTR_S39,032024_COL_SAN_T5_163_PSTR_S11c,032024_COL_SAN_T5_166_OFAV_S20,032024_COL_SAN_T5_167_OFAV_S21
56

In [8]:
otu_table=pd.read_csv("/scratch4/workspace/nikea_ulrich_uml_edu-col_data/kraken2_pluspf/bracken_filtered/ALL_col_merged_filtered_bracken_S.txt", sep='\t')

In [9]:
otu_table.set_index("taxonomy_id",inplace=True)

In [10]:
otu_table.head()

,name,taxonomy_lvl,012025_COL_SAN_T5_568_OFAV_S1_S_filtered.bracken_num,012025_COL_SAN_T5_568_OFAV_S1_S_filtered.bracken_frac,012025_COL_SAN_T5_569_DLAB_S2_S_filtered.bracken_num,012025_COL_SAN_T5_569_DLAB_S2_S_filtered.bracken_frac,012025_COL_SAN_T5_570_DLAB_S3_S_filtered.bracken_num,012025_COL_SAN_T5_570_DLAB_S3_S_filtered.bracken_frac,012025_COL_SAN_T5_571_DLAB_S4_S_filtered.bracken_num,012025_COL_SAN_T5_571_DLAB_S4_S_filtered.bracken_frac,...,032024_COL_SAN_T5_161_DLAB_S42_S_filtered.bracken_num,032024_COL_SAN_T5_161_DLAB_S42_S_filtered.bracken_frac,032024_COL_SAN_T5_162_PSTR_S39_S_filtered.bracken_num,032024_COL_SAN_T5_162_PSTR_S39_S_filtered.bracken_frac,032024_COL_SAN_T5_163_PSTR_S11c_S_filtered.bracken_num,032024_COL_SAN_T5_163_PSTR_S11c_S_filtered.bracken_frac,032024_COL_SAN_T5_166_OFAV_S20_S_filtered.bracken_num,032024_COL_SAN_T5_166_OFAV_S20_S_filtered.bracken_frac,032024_COL_SAN_T5_167_OFAV_S21_S_filtered.bracken_num,032024_COL_SAN_T5_167_OFAV_S21_S_filtered.bracken_frac
taxonomy_id,,,,,,,,,,,,,,,,,,,,,
2066072,Bacterioplanoides sp.,S,10341,0.03400,8428,0.03463,6296,0.01646,7390,0.02131,...,24346,0.02240,19879,0.02872,48080,0.06071,4513,0.03133,4480,0.03731
562,Escherichia coli,S,4890,0.01608,982,0.00403,12402,0.03241,26068,0.07516,...,14404,0.01325,2366,0.00342,3178,0.00401,2167,0.01504,1792,0.01492
28213,Sphingomonas parapaucimobilis,S,4241,0.01395,41,0.00017,212,0.00055,197,0.00057,...,171,0.00016,0,0.00000,3516,0.00444,0,0.00000,0,0.00000
2562892,Myroides albus,S,3027,0.00995,334,0.00137,530,0.00139,371,0.00107,...,770,0.00071,1668,0.00241,1190,0.00150,2031,0.01410,1585,0.01320
4779,Bremia lactucae,S,2908,0.00956,163,0.00067,142,0.00037,145,0.00042,...,889,0.00082,601,0.00087,969,0.00122,1015,0.00705,1137,0.00947

Columns: \
Sample num: Number of reads estimated for that species  \
Sample frac: Fraction of total reads in the sample estimated for this species \
[NOTE: Fractions are of total reads classified, unclassified reads not accounted for]

In [11]:
# Make taxa otu id table 
otu_id=otu_table.iloc[:, 0:2]
otu_id
# export otu id 
otu_id.to_csv("otu_id_species.csv")
#output to /bracken_filtered

In [12]:
# drop name, taxa, and frac cols
drop_columns = [col for col in otu_table.columns if 'frac' in col]
drop_columns.extend(['name', 'taxonomy_lvl'])
otu_table_species=otu_table.drop(columns=drop_columns)

# rename to drop _num
#otu_table_species.columns.str.replace('_num', '')

# export otu table to csv
otu_table_species.to_csv("otu_table_species.csv")

I think I want to normalize based on number of reads classified for each sample (after filtering out human)

I previously normalized from total reads per sample, but then that includes all the unclassified reads as well as the human classified reads. As long as we are normalizing for differences in reads per sample I think this is better.

In [27]:
# add column for number of classified reads per sample

import re
slurmdir='/work/pi_sarah_gignouxwolfsohn_uml_edu/nikea/COL/slurms/slurm-bracken-filtering-55314874_ordered.out'
#make sure the order in which kraken.outs are merged are in the same order as the samplelist
    #just had to move the 012025 samples above the 032024 (made that change quick by downloading and re-uploading

In [ ]:
#This is the pattern in the slurm output I want to pull read #s from
# 242006 reads remaining (213219 reads excluded)

In [28]:
# Read the output report and extract the total number of reads
with open(slurmdir, 'r') as file:
    report_text = file.read()

In [29]:
# Extract total number of reads using regular expression
total_reads_pattern = re.compile(r'(\d+) reads remaining')
total_reads_matches = total_reads_pattern.findall(report_text)
total_reads_matches

['304109',
 '243376',
 '382606',
 '346840',
 '376292',
 '664778',
 '147450',
 '864728',
 '594751',
 '543649',
 '166362',
 '621442',
 '362257',
 '186409',
 '823134',
 '165805',
 '308187',
 '278147',
 '293091',
 '654635',
 '175772',
 '198745',
 '1304416',
 '156569',
 '457490',
 '251412',
 '216036',
 '209934',
 '306033',
 '268752',
 '167634',
 '253276',
 '78993',
 '201029',
 '245794',
 '127787',
 '153631',
 '104220',
 '297250',
 '86564',
 '795003',
 '229220',
 '262744',
 '496982',
 '305688',
 '265622',
 '308329',
 '390453',
 '273792',
 '284971',
 '775447',
 '1086914',
 '692153',
 '792021',
 '144060',
 '120083']

In [30]:
# Create a dictionary to map sample ID to total reads
total_reads_dict = {samplelist[i]: int(total_reads_matches[i]) for i in range(len(samplelist))}

# Display the updated DataFrame
print(total_reads_dict)

{'012025_COL_SAN_T5_568_OFAV_S1': 304109, '012025_COL_SAN_T5_569_DLAB_S2': 243376, '012025_COL_SAN_T5_570_DLAB_S3': 382606, '012025_COL_SAN_T5_571_DLAB_S4': 346840, '012025_COL_SAN_T5_572_OFAV_S5': 376292, '012025_COL_SAN_T5_573_PSTR_S6': 664778, '012025_COL_SAN_T5_574_MCAV_S7': 147450, '012025_COL_SAN_T5_575_DLAB_S8': 864728, '012025_COL_SAN_T5_576_PSTR_S9': 594751, '012025_COL_SAN_T5_577_PSTR_S10': 543649, '012025_COL_SAN_T5_578_MCAV_S11': 166362, '012025_COL_SAN_T5_579_DLAB_S12': 621442, '012025_COL_SAN_T5_580_OFAV_S13': 362257, '012025_COL_SAN_T5_581_MCAV_S14': 186409, '012025_COL_SAN_T5_582_PSTR_S15': 823134, '012025_COL_SAN_T5_583_MCAV_S16': 165805, '012025_COL_SAN_T5_584_OFAV_S17': 308187, '012025_COL_SAN_T5_585_OFAV_S18': 278147, '012025_COL_SAN_T5_586_DLAB_S19': 293091, '012025_COL_SAN_T5_587_PSTR_S20': 654635, '012025_COL_SAN_T5_588_MCAV_S21': 175772, '012025_COL_SAN_T5_589_MCAV_S22': 198745, '012025_COL_SAN_T5_590_PSTR_S23': 1304416, '012025_COL_SAN_T5_591_MCAV_S24': 156569, '012025_COL_SAN_T5_592_PSTR_S25': 457490, '012025_COL_SAN_T5_593_MCAV_S26': 251412, '012025_COL_SAN_T5_594_MCAV_S27': 216036, '012025_COL_SAN_T5_595_MCAV_S28': 209934, '012025_COL_SAN_T5_596_OFAV_S29': 306033, '032024_COL_SAN_T5_128_MCAV_S1': 268752, '032024_COL_SAN_T5_129_MCAV_S2': 167634, '032024_COL_SAN_T5_130_MCAV_S37': 253276, '032024_COL_SAN_T5_131_MCAV_S3': 78993, '032024_COL_SAN_T5_132_MCAV_S4': 201029, '032024_COL_SAN_T5_133_MCAV_S5': 245794, '032024_COL_SAN_T5_134_MCAV_S6': 127787, '032024_COL_SAN_T5_136_MCAV_S7': 153631, '032024_COL_SAN_T5_139_OFAV_S17': 104220, '032024_COL_SAN_T5_140_OFAV_S18c': 297250, '032024_COL_SAN_T5_141_OFAV_S19': 86564, '032024_COL_SAN_T5_143_DLAB_S40': 795003, '032024_COL_SAN_T5_144_PSTR_S9': 229220, '032024_COL_SAN_T5_146_DLAB_S12': 262744, '032024_COL_SAN_T5_147_PSTR_S10': 496982, '032024_COL_SAN_T5_148_DLAB_S13': 305688, '032024_COL_SAN_T5_149_DLAB_S14': 265622, '032024_COL_SAN_T5_150_MCAV_S8': 308329, '032024_COL_SAN_T5_154_PSTR_S38': 390453, '032024_COL_SAN_T5_158_DLAB_S15': 273792, '032024_COL_SAN_T5_159_DLAB_S16': 284971, '032024_COL_SAN_T5_160_DLAB_S41': 775447, '032024_COL_SAN_T5_161_DLAB_S42': 1086914, '032024_COL_SAN_T5_162_PSTR_S39': 692153, '032024_COL_SAN_T5_163_PSTR_S11c': 792021, '032024_COL_SAN_T5_166_OFAV_S20': 144060, '032024_COL_SAN_T5_167_OFAV_S21': 120083}

In [31]:
# Convert main df to raw abundances 
normalized_otus=otu_table.loc[:,otu_table.columns.str.contains("num")]
#headers in the otu table need to match the all_sampleids.txt
normalized_otus.columns = normalized_otus.columns.str.replace('_S_filtered.bracken_num', '')
normalized_otus

,012025_COL_SAN_T5_568_OFAV_S1,012025_COL_SAN_T5_569_DLAB_S2,012025_COL_SAN_T5_570_DLAB_S3,012025_COL_SAN_T5_571_DLAB_S4,012025_COL_SAN_T5_572_OFAV_S5,012025_COL_SAN_T5_573_PSTR_S6,012025_COL_SAN_T5_574_MCAV_S7,012025_COL_SAN_T5_575_DLAB_S8,012025_COL_SAN_T5_576_PSTR_S9,012025_COL_SAN_T5_577_PSTR_S10,...,032024_COL_SAN_T5_150_MCAV_S8,032024_COL_SAN_T5_154_PSTR_S38,032024_COL_SAN_T5_158_DLAB_S15,032024_COL_SAN_T5_159_DLAB_S16,032024_COL_SAN_T5_160_DLAB_S41,032024_COL_SAN_T5_161_DLAB_S42,032024_COL_SAN_T5_162_PSTR_S39,032024_COL_SAN_T5_163_PSTR_S11c,032024_COL_SAN_T5_166_OFAV_S20,032024_COL_SAN_T5_167_OFAV_S21
taxonomy_id,,,,,,,,,,,,,,,,,,,,,
2066072,10341,8428,6296,7390,12692,16133,8308,9468,32804,29321,...,5107,16539,15450,17041,29316,24346,19879,48080,4513,4480
562,4890,982,12402,26068,5844,2475,1051,5145,2207,1832,...,1627,2411,1461,1359,4012,14404,2366,3178,2167,1792
28213,4241,41,212,197,4162,170,2783,3988,19,42,...,24,0,0,0,0,171,0,3516,0,0
2562892,3027,334,530,371,4304,1064,195,606,663,1037,...,370,1179,398,564,1257,770,1668,1190,2031,1585
4779,2908,163,142,145,3173,433,178,384,680,1451,...,159,530,486,498,821,889,601,969,1015,1137
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3050341,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,11,0,0
2956520,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,10,0,0
3426178,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,10,0,0
1923618,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,10,0,0
524,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,15,0

In [32]:
# Convert the dictionary to a DataFrame and transpose it
sample_counts_df = pd.DataFrame(total_reads_dict, index=['Total_reads'])
sample_counts_df

,012025_COL_SAN_T5_568_OFAV_S1,012025_COL_SAN_T5_569_DLAB_S2,012025_COL_SAN_T5_570_DLAB_S3,012025_COL_SAN_T5_571_DLAB_S4,012025_COL_SAN_T5_572_OFAV_S5,012025_COL_SAN_T5_573_PSTR_S6,012025_COL_SAN_T5_574_MCAV_S7,012025_COL_SAN_T5_575_DLAB_S8,012025_COL_SAN_T5_576_PSTR_S9,012025_COL_SAN_T5_577_PSTR_S10,...,032024_COL_SAN_T5_150_MCAV_S8,032024_COL_SAN_T5_154_PSTR_S38,032024_COL_SAN_T5_158_DLAB_S15,032024_COL_SAN_T5_159_DLAB_S16,032024_COL_SAN_T5_160_DLAB_S41,032024_COL_SAN_T5_161_DLAB_S42,032024_COL_SAN_T5_162_PSTR_S39,032024_COL_SAN_T5_163_PSTR_S11c,032024_COL_SAN_T5_166_OFAV_S20,032024_COL_SAN_T5_167_OFAV_S21
Total_reads,304109,243376,382606,346840,376292,664778,147450,864728,594751,543649,...,308329,390453,273792,284971,775447,1086914,692153,792021,144060,120083

In [33]:
# Concatenate the original DataFrame and the new DataFrame with the total reads row
normalized_otus = pd.concat([normalized_otus, sample_counts_df],axis=0)
normalized_otus

,012025_COL_SAN_T5_568_OFAV_S1,012025_COL_SAN_T5_569_DLAB_S2,012025_COL_SAN_T5_570_DLAB_S3,012025_COL_SAN_T5_571_DLAB_S4,012025_COL_SAN_T5_572_OFAV_S5,012025_COL_SAN_T5_573_PSTR_S6,012025_COL_SAN_T5_574_MCAV_S7,012025_COL_SAN_T5_575_DLAB_S8,012025_COL_SAN_T5_576_PSTR_S9,012025_COL_SAN_T5_577_PSTR_S10,...,032024_COL_SAN_T5_150_MCAV_S8,032024_COL_SAN_T5_154_PSTR_S38,032024_COL_SAN_T5_158_DLAB_S15,032024_COL_SAN_T5_159_DLAB_S16,032024_COL_SAN_T5_160_DLAB_S41,032024_COL_SAN_T5_161_DLAB_S42,032024_COL_SAN_T5_162_PSTR_S39,032024_COL_SAN_T5_163_PSTR_S11c,032024_COL_SAN_T5_166_OFAV_S20,032024_COL_SAN_T5_167_OFAV_S21
2066072,10341,8428,6296,7390,12692,16133,8308,9468,32804,29321,...,5107,16539,15450,17041,29316,24346,19879,48080,4513,4480
562,4890,982,12402,26068,5844,2475,1051,5145,2207,1832,...,1627,2411,1461,1359,4012,14404,2366,3178,2167,1792
28213,4241,41,212,197,4162,170,2783,3988,19,42,...,24,0,0,0,0,171,0,3516,0,0
2562892,3027,334,530,371,4304,1064,195,606,663,1037,...,370,1179,398,564,1257,770,1668,1190,2031,1585
4779,2908,163,142,145,3173,433,178,384,680,1451,...,159,530,486,498,821,889,601,969,1015,1137
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2956520,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,10,0,0
3426178,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,10,0,0
1923618,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,10,0,0
524,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,15,0
Total_reads,304109,243376,382606,346840,376292,664778,147450,864728,594751,543649,...,308329,390453,273792,284971,775447,1086914,692153,792021,144060,120083

In [34]:
# Normalize: divide reads by total reads and multiply by 1 million
normalized_otu = (normalized_otus / normalized_otus.loc['Total_reads'] * 1E6)
# replace total reads row again 
normalized_otu.loc['Total_reads',:]=normalized_otus.loc['Total_reads',:]
normalized_otu["Sum"]=normalized_otu.sum(axis=1)
normalized_otu.sort_values(by="Sum", ascending=False)

,012025_COL_SAN_T5_568_OFAV_S1,012025_COL_SAN_T5_569_DLAB_S2,012025_COL_SAN_T5_570_DLAB_S3,012025_COL_SAN_T5_571_DLAB_S4,012025_COL_SAN_T5_572_OFAV_S5,012025_COL_SAN_T5_573_PSTR_S6,012025_COL_SAN_T5_574_MCAV_S7,012025_COL_SAN_T5_575_DLAB_S8,012025_COL_SAN_T5_576_PSTR_S9,012025_COL_SAN_T5_577_PSTR_S10,...,032024_COL_SAN_T5_154_PSTR_S38,032024_COL_SAN_T5_158_DLAB_S15,032024_COL_SAN_T5_159_DLAB_S16,032024_COL_SAN_T5_160_DLAB_S41,032024_COL_SAN_T5_161_DLAB_S42,032024_COL_SAN_T5_162_PSTR_S39,032024_COL_SAN_T5_163_PSTR_S11c,032024_COL_SAN_T5_166_OFAV_S20,032024_COL_SAN_T5_167_OFAV_S21,Sum
Total_reads,304109.000000,243376.000000,382606.000000,346840.000000,376292.000000,664778.000000,147450.000000,864728.000000,594751.000000,543649.000000,...,390453.000000,273792.000000,284971.000000,775447.000000,1.086914e+06,692153.000000,792021.000000,144060.000000,120083.000000,2.081287e+07
2066072,34004.255053,34629.544409,16455.570482,21306.654365,33729.125254,24268.251958,56344.523567,10949.107696,55155.855139,53933.696190,...,42358.491291,56429.698457,59799.067274,37805.291658,2.239920e+04,28720.528554,60705.461093,31327.224767,37307.528959,2.224938e+06
588596,9016.503951,5012.819670,2506.494932,3087.879137,8461.513931,3736.585747,17300.779925,2685.237439,9630.921175,7922.391102,...,5219.578285,9109.104722,8920.205916,5871.452208,4.598340e+03,5267.621465,8150.036426,8586.699986,9618.347310,5.966846e+05
562,16079.760875,4034.908947,32414.546557,75158.574559,15530.492277,3723.047393,7127.839946,5949.847813,3710.796619,3369.821337,...,6174.878923,5336.167602,4768.906310,5173.790085,1.325220e+04,3418.319360,4012.519870,15042.343468,14923.011584,5.523051e+05
2057741,3235.681943,373.907041,1672.739058,429.592896,2662.825678,1177.836812,4367.582231,1691.861487,127.784569,222.570077,...,33330.516093,3962.862319,2947.668359,26347.384154,1.667933e+04,76208.583940,3746.112792,3526.308483,4205.424581,3.991175e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2478464,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,8.432893e+00
2956679,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,7.666266e+00
2956354,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,7.666266e+00
2876193,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,7.666266e+00
67313,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,7.666266e+00

In [35]:
# export otu table to csv
normalized_otu.to_csv("otu_normtable_species.csv")

This otu table still has Total_reads row and Sum column. These should be removed and add taxonomy_id label to the first column

**this notebook stops here, below is code from DR analysis in case I want to do this with COL data, delete if I decide not to**

### Now let's do phylum level

starting at step 7: reading in the phylum otu table this time

In [32]:
otu_table=pd.read_csv("/scratch4/workspace/nikea_ulrich_uml_edu-DR_data/kraken2_pluspf/bracken_filtered/DR_merged_all_bracken_P.txt", sep='\t')

In [33]:
otu_table.set_index("taxonomy_id",inplace=True)

In [34]:
otu_table.head()

,name,taxonomy_lvl,072023_Carolina_2023_Baya_052_DCYL_S9_P_filtered.bracken_num,072023_Carolina_2023_Baya_052_DCYL_S9_P_filtered.bracken_frac,072023_Carolina_2023_Baya_053_MCAV_S3_P_filtered.bracken_num,072023_Carolina_2023_Baya_053_MCAV_S3_P_filtered.bracken_frac,072023_Carolina_2023_Baya_055_MCAV_S4_P_filtered.bracken_num,072023_Carolina_2023_Baya_055_MCAV_S4_P_filtered.bracken_frac,072023_Carolina_2023_Baya_057_SSID_S7_P_filtered.bracken_num,072023_Carolina_2023_Baya_057_SSID_S7_P_filtered.bracken_frac,...,122021_Coralina_2021_Baya_029_MMEA_S23_P_filtered.bracken_num,122021_Coralina_2021_Baya_029_MMEA_S23_P_filtered.bracken_frac,122021_Coralina_2021_Baya_031_MMEA_S45_P_filtered.bracken_num,122021_Coralina_2021_Baya_031_MMEA_S45_P_filtered.bracken_frac,122021_Coralina_2021_Baya_033_PSTR7_S35_P_filtered.bracken_num,122021_Coralina_2021_Baya_033_PSTR7_S35_P_filtered.bracken_frac,122021_Coralina_2021_Baya_035_PSTR_S32_P_filtered.bracken_num,122021_Coralina_2021_Baya_035_PSTR_S32_P_filtered.bracken_frac,122021_Coralina_2021_Baya_037_PSTR_S33_P_filtered.bracken_num,122021_Coralina_2021_Baya_037_PSTR_S33_P_filtered.bracken_frac
taxonomy_id,,,,,,,,,,,,,,,,,,,,,
1224,Pseudomonadota,P,695212,0.29690,76951,0.29199,172424,0.36882,67610,0.35602,...,20559,0.31806,46821,0.35541,83615,0.29658,80795,0.32976,60802,0.31034
1239,Bacillota,P,521491,0.22271,54948,0.20850,81624,0.17459,37307,0.19645,...,14380,0.22247,30598,0.23227,63484,0.22517,56156,0.22920,41364,0.21112
976,Bacteroidota,P,346854,0.14813,39567,0.15014,64334,0.13761,25008,0.13169,...,9863,0.15259,17205,0.13060,44038,0.15620,42386,0.17300,32682,0.16681
4890,Ascomycota,P,138200,0.05902,15533,0.05894,19062,0.04077,8349,0.04396,...,2864,0.04431,4141,0.03143,13740,0.04873,0,0.00000,9307,0.04750
201174,Actinomycetota,P,131194,0.05603,18748,0.07114,28677,0.06134,20034,0.10549,...,3628,0.05613,7104,0.05393,16124,0.05719,14621,0.05967,11668,0.05955

In [35]:
# Make taxa otu id table 
otu_id=otu_table.iloc[:, 0:2]
otu_id
# export otu id 
otu_id.to_csv("otu_id_species_phylum.csv")
#output to /bracken_filtered

In [36]:
# drop name, taxa, and frac cols
drop_columns = [col for col in otu_table.columns if 'frac' in col]
drop_columns.extend(['name', 'taxonomy_lvl'])
otu_table_species=otu_table.drop(columns=drop_columns)

# rename to drop _num
#otu_table_species.columns.str.replace('_num', '')

# export otu table to csv
otu_table_species.to_csv("otu_table_species_P.csv")

In [37]:
# add column for number of classified reads per sample (doing species level right now)

import re
slurmdir='/work/pi_sarah_gignouxwolfsohn_uml_edu/nikea/DR/slurm_outs/slurm-bracken-filtering-phylum-52470654.out'
#make sure the order in which kraken.outs are merged are in the same order as the samplelist

In [38]:
# Read the output report and extract the total number of reads
with open(slurmdir, 'r') as file:
    report_text = file.read()

In [39]:
# Extract total number of reads using regular expression
total_reads_pattern = re.compile(r'(\d+) reads remaining')
total_reads_matches = total_reads_pattern.findall(report_text)
total_reads_matches

['263540',
 '467508',
 '96747',
 '127569',
 '252770',
 '100410',
 '181041',
 '2341543',
 '146066',
 '253014',
 '97657',
 '69384',
 '54554',
 '117898',
 '64639',
 '131737',
 '189905',
 '284068',
 '498168',
 '934442',
 '399235',
 '815522',
 '695201',
 '281935',
 '245012',
 '195923',
 '135854',
 '897862']

In [40]:
# Create a dictionary to map sample ID to total reads
total_reads_dict = {samplelist[i]: int(total_reads_matches[i]) for i in range(len(samplelist))}

# Display the updated DataFrame
print(total_reads_dict)

{'072023_Carolina_2023_Baya_053_MCAV_S3': 263540, '072023_Carolina_2023_Baya_055_MCAV_S4': 467508, '122021_Coralina_2021_Baya_003_MCAV_S27': 96747, '122021_Coralina_2021_Baya_005_MCAV_S28': 127569, '122021_Coralina_2021_Baya_007_MCAV_S29': 252770, '122021_Coralina_2021_Baya_017_MCAV_S30': 100410, '122021_Coralina_2021_Baya_023_MCAV_S31': 181041, '072023_Carolina_2023_Baya_052_DCYL_S9': 2341543, '072023_Carolina_2023_Baya_065_DCYL_S1': 146066, '072023_Carolina_2023_Baya_066_DCYL_S2': 253014, '122021_Coralina_2021_Baya_001_DCYL_S24': 97657, '122021_Coralina_2021_Baya_009_DCYL_S25': 69384, '122021_Coralina_2021_Baya_010_DCYL_S26': 54554, '122021_Coralina_2021_Baya_025_MMEA_S22': 117898, '122021_Coralina_2021_Baya_029_MMEA_S23': 64639, '122021_Coralina_2021_Baya_031_MMEA_S45': 131737, '072023_Carolina_2023_Baya_057_SSID_S7': 189905, '072023_Carolina_2023_Baya_059_SSID_S8': 284068, '072023_Carolina_2023_Baya_061_SSID_S5': 498168, '072023_Carolina_2023_Baya_063_SSID_S6': 934442, '122021_Coralina_2021_Baya_019_SSID1_S46': 399235, '122021_Coralina_2021_Baya_021_SSID2_S36': 815522, '122021_Coralina_2021_Baya_027_PSTR4_S34': 695201, '122021_Coralina_2021_Baya_033_PSTR7_S35': 281935, '122021_Coralina_2021_Baya_035_PSTR_S32': 245012, '122021_Coralina_2021_Baya_037_PSTR_S33': 195923, '122021_Coralina_2021_Baya_013_DLAB_S43': 135854, '122021_Coralina_2021_Baya_015_DLAB_S44': 897862}

In [41]:
# Convert main df to raw abundances 
normalized_otus=otu_table.loc[:,otu_table.columns.str.contains("num")]
#headers in the otu table need to match the all_sampleids.txt
normalized_otus.columns = normalized_otus.columns.str.replace('_P_filtered.bracken_num', '')
normalized_otus

,072023_Carolina_2023_Baya_052_DCYL_S9,072023_Carolina_2023_Baya_053_MCAV_S3,072023_Carolina_2023_Baya_055_MCAV_S4,072023_Carolina_2023_Baya_057_SSID_S7,072023_Carolina_2023_Baya_059_SSID_S8,072023_Carolina_2023_Baya_061_SSID_S5,072023_Carolina_2023_Baya_063_SSID_S6,072023_Carolina_2023_Baya_065_DCYL_S1,072023_Carolina_2023_Baya_066_DCYL_S2,122021_Coralina_2021_Baya_001_DCYL_S24,...,122021_Coralina_2021_Baya_019_SSID1_S46,122021_Coralina_2021_Baya_021_SSID2_S36,122021_Coralina_2021_Baya_023_MCAV_S31,122021_Coralina_2021_Baya_025_MMEA_S22,122021_Coralina_2021_Baya_027_PSTR4_S34,122021_Coralina_2021_Baya_029_MMEA_S23,122021_Coralina_2021_Baya_031_MMEA_S45,122021_Coralina_2021_Baya_033_PSTR7_S35,122021_Coralina_2021_Baya_035_PSTR_S32,122021_Coralina_2021_Baya_037_PSTR_S33
taxonomy_id,,,,,,,,,,,,,,,,,,,,,
1224,695212,76951,172424,67610,89936,205283,444359,42167,99550,37351,...,161428,239118,47542,36784,193268,20559,46821,83615,80795,60802
1239,521491,54948,81624,37307,59384,69983,73722,32814,39596,14601,...,70002,181590,40922,29117,155290,14380,30598,63484,56156,41364
976,346854,39567,64334,25008,40992,47540,70617,22383,35128,10445,...,47722,130071,29265,17389,102693,9863,17205,44038,42386,32682
4890,138200,15533,19062,8349,12895,14086,11750,8302,10165,3568,...,6845,44414,9519,4500,44643,2864,4141,13740,0,9307
201174,131194,18748,28677,20034,25330,64666,213773,9447,19164,13844,...,46676,42835,11774,5076,51747,3628,7104,16124,14621,11668
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3123113,25,0,22,0,14,0,12,0,0,0,...,0,12,0,0,15,0,0,0,0,0
2732412,24,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1293497,0,0,0,0,0,17,31,0,0,0,...,13,54,0,0,0,0,0,25,0,14
1154676,0,0,0,0,0,0,49,0,0,0,...,0,21,0,0,0,0,0,0,0,0
67810,0,0,0,0,0,0,14,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [42]:
# Convert the dictionary to a DataFrame and transpose it
sample_counts_df = pd.DataFrame(total_reads_dict, index=['Total_reads'])
sample_counts_df

,072023_Carolina_2023_Baya_053_MCAV_S3,072023_Carolina_2023_Baya_055_MCAV_S4,122021_Coralina_2021_Baya_003_MCAV_S27,122021_Coralina_2021_Baya_005_MCAV_S28,122021_Coralina_2021_Baya_007_MCAV_S29,122021_Coralina_2021_Baya_017_MCAV_S30,122021_Coralina_2021_Baya_023_MCAV_S31,072023_Carolina_2023_Baya_052_DCYL_S9,072023_Carolina_2023_Baya_065_DCYL_S1,072023_Carolina_2023_Baya_066_DCYL_S2,...,072023_Carolina_2023_Baya_061_SSID_S5,072023_Carolina_2023_Baya_063_SSID_S6,122021_Coralina_2021_Baya_019_SSID1_S46,122021_Coralina_2021_Baya_021_SSID2_S36,122021_Coralina_2021_Baya_027_PSTR4_S34,122021_Coralina_2021_Baya_033_PSTR7_S35,122021_Coralina_2021_Baya_035_PSTR_S32,122021_Coralina_2021_Baya_037_PSTR_S33,122021_Coralina_2021_Baya_013_DLAB_S43,122021_Coralina_2021_Baya_015_DLAB_S44
Total_reads,263540,467508,96747,127569,252770,100410,181041,2341543,146066,253014,...,498168,934442,399235,815522,695201,281935,245012,195923,135854,897862

In [43]:
# Concatenate the original DataFrame and the new DataFrame with the total reads row
normalized_otus = pd.concat([normalized_otus, sample_counts_df],axis=0)
normalized_otus

,072023_Carolina_2023_Baya_052_DCYL_S9,072023_Carolina_2023_Baya_053_MCAV_S3,072023_Carolina_2023_Baya_055_MCAV_S4,072023_Carolina_2023_Baya_057_SSID_S7,072023_Carolina_2023_Baya_059_SSID_S8,072023_Carolina_2023_Baya_061_SSID_S5,072023_Carolina_2023_Baya_063_SSID_S6,072023_Carolina_2023_Baya_065_DCYL_S1,072023_Carolina_2023_Baya_066_DCYL_S2,122021_Coralina_2021_Baya_001_DCYL_S24,...,122021_Coralina_2021_Baya_019_SSID1_S46,122021_Coralina_2021_Baya_021_SSID2_S36,122021_Coralina_2021_Baya_023_MCAV_S31,122021_Coralina_2021_Baya_025_MMEA_S22,122021_Coralina_2021_Baya_027_PSTR4_S34,122021_Coralina_2021_Baya_029_MMEA_S23,122021_Coralina_2021_Baya_031_MMEA_S45,122021_Coralina_2021_Baya_033_PSTR7_S35,122021_Coralina_2021_Baya_035_PSTR_S32,122021_Coralina_2021_Baya_037_PSTR_S33
1224,695212,76951,172424,67610,89936,205283,444359,42167,99550,37351,...,161428,239118,47542,36784,193268,20559,46821,83615,80795,60802
1239,521491,54948,81624,37307,59384,69983,73722,32814,39596,14601,...,70002,181590,40922,29117,155290,14380,30598,63484,56156,41364
976,346854,39567,64334,25008,40992,47540,70617,22383,35128,10445,...,47722,130071,29265,17389,102693,9863,17205,44038,42386,32682
4890,138200,15533,19062,8349,12895,14086,11750,8302,10165,3568,...,6845,44414,9519,4500,44643,2864,4141,13740,0,9307
201174,131194,18748,28677,20034,25330,64666,213773,9447,19164,13844,...,46676,42835,11774,5076,51747,3628,7104,16124,14621,11668
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2732412,24,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1293497,0,0,0,0,0,17,31,0,0,0,...,13,54,0,0,0,0,0,25,0,14
1154676,0,0,0,0,0,0,49,0,0,0,...,0,21,0,0,0,0,0,0,0,0
67810,0,0,0,0,0,0,14,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Total_reads,2341543,263540,467508,189905,284068,498168,934442,146066,253014,97657,...,399235,815522,181041,117898,695201,64639,131737,281935,245012,195923

In [44]:
# Normalize: divide reads by total reads and multiply by 1 million
normalized_otu = (normalized_otus / normalized_otus.loc['Total_reads'] * 1E6)
# replace total reads row again 
normalized_otu.loc['Total_reads',:]=normalized_otus.loc['Total_reads',:]
normalized_otu["Sum"]=normalized_otu.sum(axis=1)
normalized_otu.sort_values(by="Sum", ascending=False)

,072023_Carolina_2023_Baya_052_DCYL_S9,072023_Carolina_2023_Baya_053_MCAV_S3,072023_Carolina_2023_Baya_055_MCAV_S4,072023_Carolina_2023_Baya_057_SSID_S7,072023_Carolina_2023_Baya_059_SSID_S8,072023_Carolina_2023_Baya_061_SSID_S5,072023_Carolina_2023_Baya_063_SSID_S6,072023_Carolina_2023_Baya_065_DCYL_S1,072023_Carolina_2023_Baya_066_DCYL_S2,122021_Coralina_2021_Baya_001_DCYL_S24,...,122021_Coralina_2021_Baya_021_SSID2_S36,122021_Coralina_2021_Baya_023_MCAV_S31,122021_Coralina_2021_Baya_025_MMEA_S22,122021_Coralina_2021_Baya_027_PSTR4_S34,122021_Coralina_2021_Baya_029_MMEA_S23,122021_Coralina_2021_Baya_031_MMEA_S45,122021_Coralina_2021_Baya_033_PSTR7_S35,122021_Coralina_2021_Baya_035_PSTR_S32,122021_Coralina_2021_Baya_037_PSTR_S33,Sum
Total_reads,2.341543e+06,263540.000000,467508.000000,189905.000000,284068.000000,498168.000000,934442.000000,146066.000000,253014.000000,97657.000000,...,815522.000000,181041.000000,117898.000000,695201.000000,64639.000000,131737.000000,281935.000000,245012.000000,195923.000000,1.033920e+07
1224,2.969034e+05,291989.830766,368815.079100,356020.115321,316600.250644,412075.845899,475534.062039,288684.567250,393456.488574,382471.302620,...,293208.521659,262603.498655,311998.507184,278003.052355,318058.757097,355412.678291,296575.451789,329759.358725,310336.203509,9.256583e+06
1239,2.227125e+05,208499.658496,174593.803742,196450.857007,209048.537674,140480.721363,78894.142173,224651.869703,156497.268926,149513.091739,...,222667.199659,226037.195994,246967.717858,223374.247160,222466.312907,232265.802318,225172.468831,229196.937293,211123.757803,5.580043e+06
976,1.481305e+05,150136.601654,137610.479393,131686.896080,144303.476632,95429.654253,75571.303516,153238.946777,138838.167058,106955.978578,...,159494.164474,161648.466369,147491.899778,147716.991201,152585.900153,130601.121932,156199.123912,172995.608378,166810.430628,3.960489e+06
201174,5.602887e+04,71139.106018,61340.126800,105494.852690,89168.790571,129807.615102,228770.753027,64676.242247,75742.844269,141761.471272,...,52524.640660,65034.992074,43054.165465,74434.587982,56127.105927,53925.624540,57190.487169,59674.628181,59554.008463,2.224432e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2138240,5.509188e+01,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.509188e+01
2732448,3.160309e+01,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.160309e+01
67810,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,14.982203,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.498220e+01
3412625,1.153086e+01,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.153086e+01
2732412,1.024965e+01,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.024965e+01

In [46]:
# export otu table to csv
normalized_otu.to_csv("otu_normtable_species_P.csv")