In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
import os

In [4]:
os.chdir('/scratch/workspace/nikea_ulrich_uml_edu-mstracker')

In [5]:
os.chdir('/scratch/workspace/nikea_ulrich_uml_edu-mstracker/bracken_T1')

In [6]:
os.chdir('/work/pi_sarah_gignouxwolfsohn_uml_edu/nikea/COL/MST')

In [7]:
# Set path variables and create sample list 
SAMPLES='/scratch/workspace/nikea_ulrich_uml_edu-mstracker/all_wastewater_sampleids_T1.txt'
BRACKENS='/scratch/workspace/nikea_ulrich_uml_edu-mstracker/bracken_T1'
samplelist=[]

with open(SAMPLES) as samples:
    for line in samples:
        samplelist.append(line.strip())
print(samplelist)

sample_names_string = ','.join(samplelist)
print(sample_names_string)
print(len(samplelist))

['032024_COL_SAN_T5_128_MCAV_S1', '032024_COL_SAN_T5_129_MCAV_S2', '032024_COL_SAN_T5_130_MCAV_S37', '032024_COL_SAN_T5_131_MCAV_S3', '032024_COL_SAN_T5_132_MCAV_S4', '032024_COL_SAN_T5_133_MCAV_S5', '032024_COL_SAN_T5_134_MCAV_S6', '032024_COL_SAN_T5_136_MCAV_S7', '032024_COL_SAN_T5_139_OFAV_S17', '032024_COL_SAN_T5_140_OFAV_S18', '032024_COL_SAN_T5_141_OFAV_S19', '032024_COL_SAN_T5_143_DLAB_S40', '032024_COL_SAN_T5_144_PSTR_S9', '032024_COL_SAN_T5_146_DLAB_S12', '032024_COL_SAN_T5_147_PSTR_S10', '032024_COL_SAN_T5_148_DLAB_S13', '032024_COL_SAN_T5_149_DLAB_S14', '032024_COL_SAN_T5_150_MCAV_S8', '032024_COL_SAN_T5_154_PSTR_S38', '032024_COL_SAN_T5_158_DLAB_S15', '032024_COL_SAN_T5_159_DLAB_S16', '032024_COL_SAN_T5_160_DLAB_S41', '032024_COL_SAN_T5_161_DLAB_S42', '032024_COL_SAN_T5_162_PSTR_S39', '032024_COL_SAN_T5_163_PSTR_S11', '032024_COL_SAN_T5_166_OFAV_S20', '032024_COL_SAN_T5_167_OFAV_S21', 'ERR1713346', 'SRR10990426', 'SRR8573788', 'SRR8573789', 'SRR8573790', 'SRR8573791', 'SRR8573793', 'SRR8573796']
032024_COL_SAN_T5_128_MCAV_S1,032024_COL_SAN_T5_129_MCAV_S2,032024_COL_SAN_T5_130_MCAV_S37,032024_COL_SAN_T5_131_MCAV_S3,032024_COL_SAN_T5_132_MCAV_S4,032024_COL_SAN_T5_133_MCAV_S5,032024_COL_SAN_T5_134_MCAV_S6,032024_COL_SAN_T5_136_MCAV_S7,032024_COL_SAN_T5_139_OFAV_S17,032024_COL_SAN_T5_140_OFAV_S18,032024_COL_SAN_T5_141_OFAV_S19,032024_COL_SAN_T5_143_DLAB_S40,032024_COL_SAN_T5_144_PSTR_S9,032024_COL_SAN_T5_146_DLAB_S12,032024_COL_SAN_T5_147_PSTR_S10,032024_COL_SAN_T5_148_DLAB_S13,032024_COL_SAN_T5_149_DLAB_S14,032024_COL_SAN_T5_150_MCAV_S8,032024_COL_SAN_T5_154_PSTR_S38,032024_COL_SAN_T5_158_DLAB_S15,032024_COL_SAN_T5_159_DLAB_S16,032024_COL_SAN_T5_160_DLAB_S41,032024_COL_SAN_T5_161_DLAB_S42,032024_COL_SAN_T5_162_PSTR_S39,032024_COL_SAN_T5_163_PSTR_S11,032024_COL_SAN_T5_166_OFAV_S20,032024_COL_SAN_T5_167_OFAV_S21,ERR1713346,SRR10990426,SRR8573788,SRR8573789,SRR8573790,SRR8573791,SRR8573793,SRR8573796
35

In [25]:
otu_table=pd.read_csv("/work/pi_sarah_gignouxwolfsohn_uml_edu/nikea/COL/MST/COL_wastewater_merged_bracken_species_T1.txt", sep='\t')
#make sure this OTU table has the _S.bracken removed in the sample headings

for some reason I needed to copy the merged table to my work directory for it to actually read it. idk why but at least it worked

In [26]:
otu_table.set_index("taxonomy_id",inplace=True)

In [27]:
otu_table.head()

,name,taxonomy_lvl,032024_COL_SAN_T5_128_MCAV_S1_num,032024_COL_SAN_T5_128_MCAV_S1_frac,032024_COL_SAN_T5_129_MCAV_S2_num,032024_COL_SAN_T5_129_MCAV_S2_frac,032024_COL_SAN_T5_130_MCAV_S37_num,032024_COL_SAN_T5_130_MCAV_S37_frac,032024_COL_SAN_T5_131_MCAV_S3_num,032024_COL_SAN_T5_131_MCAV_S3_frac,...,SRR8573789_num,SRR8573789_frac,SRR8573790_num,SRR8573790_frac,SRR8573791_num,SRR8573791_frac,SRR8573793_num,SRR8573793_frac,SRR8573796_num,SRR8573796_frac
taxonomy_id,,,,,,,,,,,,,,,,,,,,,
2546356,Gloeothece citriformis,S,2498,0.00438,89,0.00023,68,0.00011,33,0.00013,...,39,0.00001,30,0.00001,17,0.0,15,0.0,35,0.00001
2546359,Gloeothece verrucosa,S,1925,0.00337,79,0.00020,99,0.00017,84,0.00033,...,47,0.00002,18,0.00000,24,0.0,18,0.0,52,0.00002
2546366,Rippkaea orientalis,S,3653,0.00640,65,0.00017,190,0.00032,28,0.00011,...,39,0.00001,14,0.00000,19,0.0,13,0.0,28,0.00001
2546360,Crocosphaera subtropica,S,2164,0.00379,24,0.00006,34,0.00006,30,0.00012,...,50,0.00002,17,0.00000,19,0.0,16,0.0,39,0.00001
713887,Candidatus Atelocyanobacterium thalassa,S,809,0.00142,40,0.00010,15,0.00003,0,0.00000,...,59,0.00002,28,0.00000,25,0.0,19,0.0,60,0.00002

Columns: \
Sample num: Number of reads estimated for that species  \
Sample frac: Fraction of total reads in the sample estimated for this species \
[NOTE: Fractions are of total reads classified, unclassified reads not accounted for]

In [28]:
# Make taxa otu id table 
otu_id=otu_table.iloc[:, 0:2]
otu_id
# export otu id 
otu_id.to_csv("otu_id_species.csv")

In [29]:
# drop name, taxa, and frac cols
drop_columns = [col for col in otu_table.columns if 'frac' in col]
drop_columns.extend(['name', 'taxonomy_lvl'])
otu_table_species=otu_table.drop(columns=drop_columns)

# rename to drop _num
otu_table_species.columns.str.replace('_num', '')

# remove homo sapien (9606)
otu_table_species.drop(9606,axis=0,inplace=True)
# export otu table to csv
otu_table_species.to_csv("otu_table_species.csv")

paths to kraken output where total reads can be found: /scratch3/workspace/nikea_ulrich_uml_edu-gtdb/kraken2 kraken output separated by coral species. need to normalize these abundances by total sequence

**got as far as this. need to merged 3 different kraken outputs to continue. I think I will proceed with SourceTracker with this OTU table (non-normalized) just to see if what happens and will return to this!** returned to this 7/21

In [30]:
# add column for normalized abundances for TOTAL number of reads per sample
#concatenated slurm.outs from each species into one file

import re
slurmdir='/work/pi_sarah_gignouxwolfsohn_uml_edu/nikea/COL/MST/merged_all_slurm-kraken.out'
#make sure the order in which kraken.outs are merged are in the same order as the samplelist

In [31]:
# Read the output report and extract the total number of reads
with open(slurmdir, 'r') as file:
    report_text = file.read()

In [32]:
# Extract total number of reads using regular expression
total_reads_pattern = re.compile(r'(\d+) sequences \(.* Mbp\) processed')
total_reads_matches = total_reads_pattern.findall(report_text)
total_reads_matches

['8874663',
 '7323201',
 '9403989',
 '5543107',
 '9602578',
 '8203214',
 '7790048',
 '7995111',
 '11345852',
 '11038342',
 '9716533',
 '30238675',
 '20965683',
 '16642889',
 '22502329',
 '17864752',
 '18233681',
 '8440442',
 '18562351',
 '17550481',
 '19910793',
 '32298606',
 '35872533',
 '27637202',
 '17677180',
 '12497183',
 '11425697',
 '28198167',
 '54573',
 '15116776',
 '17275697',
 '15022626',
 '14138124',
 '12123846',
 '15687315']

In [33]:
# Create a dictionary to map sample ID to total reads
total_reads_dict = {samplelist[i]: int(total_reads_matches[i]) for i in range(len(samplelist))}

# Display the updated DataFrame
print(total_reads_dict)

{'032024_COL_SAN_T5_128_MCAV_S1': 8874663, '032024_COL_SAN_T5_129_MCAV_S2': 7323201, '032024_COL_SAN_T5_130_MCAV_S37': 9403989, '032024_COL_SAN_T5_131_MCAV_S3': 5543107, '032024_COL_SAN_T5_132_MCAV_S4': 9602578, '032024_COL_SAN_T5_133_MCAV_S5': 8203214, '032024_COL_SAN_T5_134_MCAV_S6': 7790048, '032024_COL_SAN_T5_136_MCAV_S7': 7995111, '032024_COL_SAN_T5_139_OFAV_S17': 11345852, '032024_COL_SAN_T5_140_OFAV_S18': 11038342, '032024_COL_SAN_T5_141_OFAV_S19': 9716533, '032024_COL_SAN_T5_143_DLAB_S40': 30238675, '032024_COL_SAN_T5_144_PSTR_S9': 20965683, '032024_COL_SAN_T5_146_DLAB_S12': 16642889, '032024_COL_SAN_T5_147_PSTR_S10': 22502329, '032024_COL_SAN_T5_148_DLAB_S13': 17864752, '032024_COL_SAN_T5_149_DLAB_S14': 18233681, '032024_COL_SAN_T5_150_MCAV_S8': 8440442, '032024_COL_SAN_T5_154_PSTR_S38': 18562351, '032024_COL_SAN_T5_158_DLAB_S15': 17550481, '032024_COL_SAN_T5_159_DLAB_S16': 19910793, '032024_COL_SAN_T5_160_DLAB_S41': 32298606, '032024_COL_SAN_T5_161_DLAB_S42': 35872533, '032024_COL_SAN_T5_162_PSTR_S39': 27637202, '032024_COL_SAN_T5_163_PSTR_S11': 17677180, '032024_COL_SAN_T5_166_OFAV_S20': 12497183, '032024_COL_SAN_T5_167_OFAV_S21': 11425697, 'ERR1713346': 28198167, 'SRR10990426': 54573, 'SRR8573788': 15116776, 'SRR8573789': 17275697, 'SRR8573790': 15022626, 'SRR8573791': 14138124, 'SRR8573793': 12123846, 'SRR8573796': 15687315}

In [34]:
# Convert main df to raw abundances 
normalized_otus=otu_table.loc[:,otu_table.columns.str.contains("num")]
normalized_otus.columns = normalized_otus.columns.str.replace('_num', '')
normalized_otus

,032024_COL_SAN_T5_128_MCAV_S1,032024_COL_SAN_T5_129_MCAV_S2,032024_COL_SAN_T5_130_MCAV_S37,032024_COL_SAN_T5_131_MCAV_S3,032024_COL_SAN_T5_132_MCAV_S4,032024_COL_SAN_T5_133_MCAV_S5,032024_COL_SAN_T5_134_MCAV_S6,032024_COL_SAN_T5_136_MCAV_S7,032024_COL_SAN_T5_139_OFAV_S17,032024_COL_SAN_T5_140_OFAV_S18,...,032024_COL_SAN_T5_166_OFAV_S20,032024_COL_SAN_T5_167_OFAV_S21,ERR1713346,SRR10990426,SRR8573788,SRR8573789,SRR8573790,SRR8573791,SRR8573793,SRR8573796
taxonomy_id,,,,,,,,,,,,,,,,,,,,,
2546356,2498,89,68,33,965,2775,49,97,41,43,...,43,60,59,0,42,39,30,17,15,35
2546359,1925,79,99,84,811,2020,119,77,58,37,...,52,36,127,0,13,47,18,24,18,52
2546366,3653,65,190,28,1199,3680,56,51,168,226,...,361,249,34,0,26,39,14,19,13,28
2546360,2164,24,34,30,746,2343,20,48,0,12,...,12,10,103,0,38,50,17,19,16,39
713887,809,40,15,0,289,896,14,14,0,11,...,0,48,89,0,43,59,28,25,19,60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2844109,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,31
1982219,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,84
2955427,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,26
2846046,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,167
345201,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,28

In [35]:
# Convert the dictionary to a DataFrame and transpose it
sample_counts_df = pd.DataFrame(total_reads_dict, index=['Total_reads'])
sample_counts_df

,032024_COL_SAN_T5_128_MCAV_S1,032024_COL_SAN_T5_129_MCAV_S2,032024_COL_SAN_T5_130_MCAV_S37,032024_COL_SAN_T5_131_MCAV_S3,032024_COL_SAN_T5_132_MCAV_S4,032024_COL_SAN_T5_133_MCAV_S5,032024_COL_SAN_T5_134_MCAV_S6,032024_COL_SAN_T5_136_MCAV_S7,032024_COL_SAN_T5_139_OFAV_S17,032024_COL_SAN_T5_140_OFAV_S18,...,032024_COL_SAN_T5_166_OFAV_S20,032024_COL_SAN_T5_167_OFAV_S21,ERR1713346,SRR10990426,SRR8573788,SRR8573789,SRR8573790,SRR8573791,SRR8573793,SRR8573796
Total_reads,8874663,7323201,9403989,5543107,9602578,8203214,7790048,7995111,11345852,11038342,...,12497183,11425697,28198167,54573,15116776,17275697,15022626,14138124,12123846,15687315

In [36]:
# Concatenate the original DataFrame and the new DataFrame with the total reads row
normalized_otus = pd.concat([normalized_otus, sample_counts_df],axis=0)
normalized_otus

,032024_COL_SAN_T5_128_MCAV_S1,032024_COL_SAN_T5_129_MCAV_S2,032024_COL_SAN_T5_130_MCAV_S37,032024_COL_SAN_T5_131_MCAV_S3,032024_COL_SAN_T5_132_MCAV_S4,032024_COL_SAN_T5_133_MCAV_S5,032024_COL_SAN_T5_134_MCAV_S6,032024_COL_SAN_T5_136_MCAV_S7,032024_COL_SAN_T5_139_OFAV_S17,032024_COL_SAN_T5_140_OFAV_S18,...,032024_COL_SAN_T5_166_OFAV_S20,032024_COL_SAN_T5_167_OFAV_S21,ERR1713346,SRR10990426,SRR8573788,SRR8573789,SRR8573790,SRR8573791,SRR8573793,SRR8573796
2546356,2498,89,68,33,965,2775,49,97,41,43,...,43,60,59,0,42,39,30,17,15,35
2546359,1925,79,99,84,811,2020,119,77,58,37,...,52,36,127,0,13,47,18,24,18,52
2546366,3653,65,190,28,1199,3680,56,51,168,226,...,361,249,34,0,26,39,14,19,13,28
2546360,2164,24,34,30,746,2343,20,48,0,12,...,12,10,103,0,38,50,17,19,16,39
713887,809,40,15,0,289,896,14,14,0,11,...,0,48,89,0,43,59,28,25,19,60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1982219,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,84
2955427,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,26
2846046,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,167
345201,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,28
Total_reads,8874663,7323201,9403989,5543107,9602578,8203214,7790048,7995111,11345852,11038342,...,12497183,11425697,28198167,54573,15116776,17275697,15022626,14138124,12123846,15687315

In [37]:
# Normalize: divide reads by total reads and multiply by 1 million
normalized_otu = (normalized_otus / normalized_otus.loc['Total_reads'] * 1E6)
# replace total reads row again 
normalized_otu.loc['Total_reads',:]=normalized_otus.loc['Total_reads',:]
normalized_otu["Sum"]=normalized_otu.sum(axis=1)
normalized_otu.sort_values(by="Sum", ascending=False)

,032024_COL_SAN_T5_128_MCAV_S1,032024_COL_SAN_T5_129_MCAV_S2,032024_COL_SAN_T5_130_MCAV_S37,032024_COL_SAN_T5_131_MCAV_S3,032024_COL_SAN_T5_132_MCAV_S4,032024_COL_SAN_T5_133_MCAV_S5,032024_COL_SAN_T5_134_MCAV_S6,032024_COL_SAN_T5_136_MCAV_S7,032024_COL_SAN_T5_139_OFAV_S17,032024_COL_SAN_T5_140_OFAV_S18,...,032024_COL_SAN_T5_167_OFAV_S21,ERR1713346,SRR10990426,SRR8573788,SRR8573789,SRR8573790,SRR8573791,SRR8573793,SRR8573796,Sum
Total_reads,8.874663e+06,7.323201e+06,9.403989e+06,5.543107e+06,9.602578e+06,8.203214e+06,7.790048e+06,7.995111e+06,1.134585e+07,1.103834e+07,...,1.142570e+07,2.819817e+07,54573.000000,1.511678e+07,1.727570e+07,1.502263e+07,1.413812e+07,1.212385e+07,1.568732e+07,5.427742e+08
9606,2.848998e+04,2.505762e+04,3.279194e+04,2.564573e+04,2.388463e+04,2.638015e+04,2.508316e+04,2.608344e+04,2.564162e+04,2.597673e+04,...,2.639244e+04,3.063816e+03,842.907665,2.584347e+03,8.516010e+03,2.008304e+03,1.985412e+03,5.244375e+03,1.188731e+04,6.500088e+05
1986204,2.366287e+00,5.188988e+00,1.701406e+00,2.706064e+00,3.020022e+00,0.000000e+00,3.722698e+00,4.127522e+00,2.379724e+00,1.087120e+00,...,2.100528e+00,1.464634e+01,120957.249922,4.167555e+00,3.183663e+00,2.529518e+00,1.909730e+00,1.649642e+00,2.613577e+00,1.211663e+05
456827,0.000000e+00,0.000000e+00,1.595068e+00,0.000000e+00,0.000000e+00,1.828552e+00,1.412058e+00,0.000000e+00,6.962897e+00,4.439072e+00,...,3.763447e+00,4.397449e+00,117695.563740,3.836797e+00,6.020018e+00,2.396385e+00,1.768269e+00,7.588351e+00,2.868560e+00,1.177792e+05
296,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.364543e+00,3.377064e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,3.399157e+02,0.000000,1.772865e+01,6.589662e+03,7.163568e+04,2.232977e+04,7.680896e+03,3.091670e+01,1.086561e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2734145,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.787648e-01
3050281,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.787648e-01
2734263,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.787648e-01
2734149,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.787648e-01
537874,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.787648e-01

In [38]:
# export otu table to csv
normalized_otu.to_csv("otu_normtable_species.csv")

Combine tables in R so that the OTU table has the taxa names as well.

This otu table still has Total_reads row and Sum column. These should be removed. Also lots of hits to homo sapien (tax id: 9606), so should remove this too. Did this in otu_normtable_species_ready.csv

## Let's do this with CBC data to compare

### files I'm using 
S.bracken files \
sample IDs list \
kraken.out files with the number of sequences for each sample...for normalizing purposes \
the wastewater samples that I had the most detected from with COL dataset (n=6)

In [5]:
os.chdir('/work/pi_sarah_gignouxwolfsohn_uml_edu/nikea/COL/MST/cbc_brooke_data/all_brackens')

In [6]:
os.chdir('/work/pi_sarah_gignouxwolfsohn_uml_edu/nikea/COL/MST/cbc_brooke_data')

In [8]:
# Set path variables and create sample list 
SAMPLES='/work/pi_sarah_gignouxwolfsohn_uml_edu/nikea/COL/MST/cbc_brooke_data/sample_list.txt'
BRACKENS='/work/pi_sarah_gignouxwolfsohn_uml_edu/nikea/COL/MST/cbc_brooke_data/all_brackens'
samplelist=[]

with open(SAMPLES) as samples:
    for line in samples:
        samplelist.append(line.strip())
print(samplelist)

sample_names_string = ','.join(samplelist)
print(sample_names_string)
print(len(samplelist))

['052022_BEL_CBC_T2_45_PSTR', '102019_BEL_CBC_T1_28_PSTR', '102019_BEL_CBC_T1_29_PSTR', '052022_BEL_CBC_T2_46_PSTR', '052022_BEL_CBC_T1_4_PSTR', '102019_BEL_CBC_T1_25_PSTR', '052022_BEL_CBC_T3_15_PSTR', '052022_BEL_CBC_T3_3_PSTR', '102019_BEL_CBC_T1_27_PSTR', '052022_BEL_CBC_T2_14_PSTR', '052022_BEL_CBC_T1_10_PSTR', '102019_BEL_CBC_T1_26_PSTR', '052022_BEL_CBC_T2_13_PSTR', '052022_BEL_CBC_T1_11_PSTR', '102019_BEL_CBC_T2_32_PSTR', '102019_BEL_CBC_T1_30_PSTR', '102019_BEL_CBC_T2_33_PSTR', '102019_BEL_CBC_T1_31_PSTR', '102019_BEL_CBC_T2_30_PSTR', '102019_BEL_CBC_T2_31_PSTR', '102019_BEL_CBC_T3_37_PSTR', '102019_BEL_CBC_T2_36_PSTR', '052022_BEL_CBC_T2_7_PSTR', '102019_BEL_CBC_T3_36_PSTR', '102019_BEL_CBC_T3_40_PSTR', '102019_BEL_CBC_T3_35_PSTR', '102019_BEL_CBC_T2_34_PSTR', '102019_BEL_CBC_T3_34_PSTR', '052022_BEL_CBC_T3_23_PSTR', '102019_BEL_CBC_T3_38_PSTR', '052022_BEL_CBC_T2_8_PSTR', '102019_BEL_CBC_T3_39_PSTR', '052022_BEL_CBC_T1_55_PSTR', 'SRR8573788', 'SRR8573789', 'SRR8573790', 'SRR8573791', 'SRR8573793', 'SRR8573796']
052022_BEL_CBC_T2_45_PSTR,102019_BEL_CBC_T1_28_PSTR,102019_BEL_CBC_T1_29_PSTR,052022_BEL_CBC_T2_46_PSTR,052022_BEL_CBC_T1_4_PSTR,102019_BEL_CBC_T1_25_PSTR,052022_BEL_CBC_T3_15_PSTR,052022_BEL_CBC_T3_3_PSTR,102019_BEL_CBC_T1_27_PSTR,052022_BEL_CBC_T2_14_PSTR,052022_BEL_CBC_T1_10_PSTR,102019_BEL_CBC_T1_26_PSTR,052022_BEL_CBC_T2_13_PSTR,052022_BEL_CBC_T1_11_PSTR,102019_BEL_CBC_T2_32_PSTR,102019_BEL_CBC_T1_30_PSTR,102019_BEL_CBC_T2_33_PSTR,102019_BEL_CBC_T1_31_PSTR,102019_BEL_CBC_T2_30_PSTR,102019_BEL_CBC_T2_31_PSTR,102019_BEL_CBC_T3_37_PSTR,102019_BEL_CBC_T2_36_PSTR,052022_BEL_CBC_T2_7_PSTR,102019_BEL_CBC_T3_36_PSTR,102019_BEL_CBC_T3_40_PSTR,102019_BEL_CBC_T3_35_PSTR,102019_BEL_CBC_T2_34_PSTR,102019_BEL_CBC_T3_34_PSTR,052022_BEL_CBC_T3_23_PSTR,102019_BEL_CBC_T3_38_PSTR,052022_BEL_CBC_T2_8_PSTR,102019_BEL_CBC_T3_39_PSTR,052022_BEL_CBC_T1_55_PSTR,SRR8573788,SRR8573789,SRR8573790,SRR8573791,SRR8573793,SRR8573796
39

In [ ]:
#needed a combined OTU table of all bracken outputs, did this in commandline
python combine_bracken_outputs.py --files *.bracken --output merged_PSTR_wastewater_bracken_otus.txt

#for some reason I couldn't get Brooke's cbc mcavs to combine with the others so proceeding with just the PSTRs

In [9]:
otu_table=pd.read_csv("/work/pi_sarah_gignouxwolfsohn_uml_edu/nikea/COL/MST/cbc_brooke_data/merged_PSTR_wastewater_bracken_otus.txt", sep='\t')
#make sure this OTU table has the _S.bracken removed in the sample headings

In [10]:
otu_table.set_index("taxonomy_id",inplace=True)

In [11]:
otu_table.head()

,name,taxonomy_lvl,052022_BEL_CBC_T1_10_PSTR_num,052022_BEL_CBC_T1_10_PSTR_frac,052022_BEL_CBC_T1_11_PSTR_num,052022_BEL_CBC_T1_11_PSTR_frac,052022_BEL_CBC_T1_4_PSTR_num,052022_BEL_CBC_T1_4_PSTR_frac,052022_BEL_CBC_T1_55_PSTR_num,052022_BEL_CBC_T1_55_PSTR_frac,...,SRR8573789_num,SRR8573789_frac,SRR8573790_num,SRR8573790_frac,SRR8573791_num,SRR8573791_frac,SRR8573793_num,SRR8573793_frac,SRR8573796_num,SRR8573796_frac
taxonomy_id,,,,,,,,,,,,,,,,,,,,,
3021011,Vibrio sp. SCSIO 43137,S,8075,0.01507,8,0.00002,7,0.00002,12,0.00001,...,32,0.00001,30,0.00001,53,0.00001,42,0.00001,47,0.00002
2819098,Vibrio sp. SCSIO 43153,S,2206,0.00412,173,0.00037,0,0.00000,10,0.00001,...,0,0.00000,0,0.00000,0,0.00000,0,0.00000,0,0.00000
2912314,Vibrio sp. JC009,S,99,0.00018,40,0.00008,35,0.00010,60,0.00007,...,21,0.00001,0,0.00000,25,0.00000,43,0.00001,43,0.00002
2785746,Vibrio sp. VB16,S,90,0.00017,85,0.00018,75,0.00022,133,0.00016,...,24,0.00001,0,0.00000,23,0.00000,93,0.00002,25,0.00001
2751176,Vibrio sp. B1ASS3,S,119,0.00022,1173,0.00248,12,0.00004,5,0.00001,...,0,0.00000,0,0.00000,0,0.00000,0,0.00000,0,0.00000

In [12]:
# Make taxa otu id table 
otu_id=otu_table.iloc[:, 0:2]
otu_id
# export otu id 
otu_id.to_csv("otu_id_species.csv")

In [13]:
# drop name, taxa, and frac cols
drop_columns = [col for col in otu_table.columns if 'frac' in col]
drop_columns.extend(['name', 'taxonomy_lvl'])
otu_table_species=otu_table.drop(columns=drop_columns)

# rename to drop _num
otu_table_species.columns.str.replace('_num', '')

# remove homo sapien (9606)
otu_table_species.drop(9606,axis=0,inplace=True)
# export otu table to csv
otu_table_species.to_csv("otu_table_species.csv")

In [16]:
# add column for normalized abundances for TOTAL number of reads per sample
#concatenated slurm.outs from each species into one file

import re
slurmdir='/work/pi_sarah_gignouxwolfsohn_uml_edu/nikea/COL/MST/cbc_brooke_data/slurm-merged.txt'
#make sure the order in which kraken.outs are merged are in the same order as the samplelist

In [17]:
# Read the output report and extract the total number of reads
with open(slurmdir, 'r') as file:
    report_text = file.read()

In [18]:
# Extract total number of reads using regular expression
total_reads_pattern = re.compile(r'(\d+) sequences \(.* Mbp\) processed')
total_reads_matches = total_reads_pattern.findall(report_text)
total_reads_matches

['32901040',
 '23159221',
 '16020690',
 '17351886',
 '18763016',
 '24196261',
 '29615054',
 '43828341',
 '21196862',
 '23416543',
 '25723079',
 '10887256',
 '18950755',
 '25386963',
 '14265228',
 '30869362',
 '32953155',
 '18273682',
 '21259800',
 '10660464',
 '24769854',
 '31213609',
 '10636072',
 '34021149',
 '29595491',
 '25666947',
 '26606935',
 '30646029',
 '27629625',
 '35938893',
 '35413053',
 '16950294',
 '41309990',
 '15116776',
 '17275697',
 '15022626',
 '14138124',
 '12123846',
 '15687315']

In [19]:
# Create a dictionary to map sample ID to total reads
total_reads_dict = {samplelist[i]: int(total_reads_matches[i]) for i in range(len(samplelist))}

# Display the updated DataFrame
print(total_reads_dict)

{'052022_BEL_CBC_T2_45_PSTR': 32901040, '102019_BEL_CBC_T1_28_PSTR': 23159221, '102019_BEL_CBC_T1_29_PSTR': 16020690, '052022_BEL_CBC_T2_46_PSTR': 17351886, '052022_BEL_CBC_T1_4_PSTR': 18763016, '102019_BEL_CBC_T1_25_PSTR': 24196261, '052022_BEL_CBC_T3_15_PSTR': 29615054, '052022_BEL_CBC_T3_3_PSTR': 43828341, '102019_BEL_CBC_T1_27_PSTR': 21196862, '052022_BEL_CBC_T2_14_PSTR': 23416543, '052022_BEL_CBC_T1_10_PSTR': 25723079, '102019_BEL_CBC_T1_26_PSTR': 10887256, '052022_BEL_CBC_T2_13_PSTR': 18950755, '052022_BEL_CBC_T1_11_PSTR': 25386963, '102019_BEL_CBC_T2_32_PSTR': 14265228, '102019_BEL_CBC_T1_30_PSTR': 30869362, '102019_BEL_CBC_T2_33_PSTR': 32953155, '102019_BEL_CBC_T1_31_PSTR': 18273682, '102019_BEL_CBC_T2_30_PSTR': 21259800, '102019_BEL_CBC_T2_31_PSTR': 10660464, '102019_BEL_CBC_T3_37_PSTR': 24769854, '102019_BEL_CBC_T2_36_PSTR': 31213609, '052022_BEL_CBC_T2_7_PSTR': 10636072, '102019_BEL_CBC_T3_36_PSTR': 34021149, '102019_BEL_CBC_T3_40_PSTR': 29595491, '102019_BEL_CBC_T3_35_PSTR': 25666947, '102019_BEL_CBC_T2_34_PSTR': 26606935, '102019_BEL_CBC_T3_34_PSTR': 30646029, '052022_BEL_CBC_T3_23_PSTR': 27629625, '102019_BEL_CBC_T3_38_PSTR': 35938893, '052022_BEL_CBC_T2_8_PSTR': 35413053, '102019_BEL_CBC_T3_39_PSTR': 16950294, '052022_BEL_CBC_T1_55_PSTR': 41309990, 'SRR8573788': 15116776, 'SRR8573789': 17275697, 'SRR8573790': 15022626, 'SRR8573791': 14138124, 'SRR8573793': 12123846, 'SRR8573796': 15687315}

In [20]:
# Convert main df to raw abundances 
normalized_otus=otu_table.loc[:,otu_table.columns.str.contains("num")]
normalized_otus.columns = normalized_otus.columns.str.replace('_num', '')
normalized_otus

,052022_BEL_CBC_T1_10_PSTR,052022_BEL_CBC_T1_11_PSTR,052022_BEL_CBC_T1_4_PSTR,052022_BEL_CBC_T1_55_PSTR,052022_BEL_CBC_T2_13_PSTR,052022_BEL_CBC_T2_14_PSTR,052022_BEL_CBC_T2_45_PSTR,052022_BEL_CBC_T2_46_PSTR,052022_BEL_CBC_T2_7_PSTR,052022_BEL_CBC_T2_8_PSTR,...,102019_BEL_CBC_T3_37_PSTR,102019_BEL_CBC_T3_38_PSTR,102019_BEL_CBC_T3_39_PSTR,102019_BEL_CBC_T3_40_PSTR,SRR8573788,SRR8573789,SRR8573790,SRR8573791,SRR8573793,SRR8573796
taxonomy_id,,,,,,,,,,,,,,,,,,,,,
3021011,8075,8,7,12,26,9,92,9,11,15,...,7,4,1,5,18,32,30,53,42,47
2819098,2206,173,0,10,18,8,76,0,3,37,...,3,1,9,20,0,0,0,0,0,0
2912314,99,40,35,60,36,44,72,0,9,69,...,39,46,26,47,25,21,0,25,43,43
2785746,90,85,75,133,28,96,115,2,26,161,...,120,131,52,118,19,24,0,23,93,25
2751176,119,1173,12,5,39,0,355,0,11,231,...,0,0,14,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2032563,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2032573,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1298531,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
693627,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
693629,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [21]:
# Convert the dictionary to a DataFrame and transpose it
sample_counts_df = pd.DataFrame(total_reads_dict, index=['Total_reads'])
sample_counts_df

,052022_BEL_CBC_T2_45_PSTR,102019_BEL_CBC_T1_28_PSTR,102019_BEL_CBC_T1_29_PSTR,052022_BEL_CBC_T2_46_PSTR,052022_BEL_CBC_T1_4_PSTR,102019_BEL_CBC_T1_25_PSTR,052022_BEL_CBC_T3_15_PSTR,052022_BEL_CBC_T3_3_PSTR,102019_BEL_CBC_T1_27_PSTR,052022_BEL_CBC_T2_14_PSTR,...,102019_BEL_CBC_T3_38_PSTR,052022_BEL_CBC_T2_8_PSTR,102019_BEL_CBC_T3_39_PSTR,052022_BEL_CBC_T1_55_PSTR,SRR8573788,SRR8573789,SRR8573790,SRR8573791,SRR8573793,SRR8573796
Total_reads,32901040,23159221,16020690,17351886,18763016,24196261,29615054,43828341,21196862,23416543,...,35938893,35413053,16950294,41309990,15116776,17275697,15022626,14138124,12123846,15687315

In [22]:
# Concatenate the original DataFrame and the new DataFrame with the total reads row
normalized_otus = pd.concat([normalized_otus, sample_counts_df],axis=0)
normalized_otus

,052022_BEL_CBC_T1_10_PSTR,052022_BEL_CBC_T1_11_PSTR,052022_BEL_CBC_T1_4_PSTR,052022_BEL_CBC_T1_55_PSTR,052022_BEL_CBC_T2_13_PSTR,052022_BEL_CBC_T2_14_PSTR,052022_BEL_CBC_T2_45_PSTR,052022_BEL_CBC_T2_46_PSTR,052022_BEL_CBC_T2_7_PSTR,052022_BEL_CBC_T2_8_PSTR,...,102019_BEL_CBC_T3_37_PSTR,102019_BEL_CBC_T3_38_PSTR,102019_BEL_CBC_T3_39_PSTR,102019_BEL_CBC_T3_40_PSTR,SRR8573788,SRR8573789,SRR8573790,SRR8573791,SRR8573793,SRR8573796
3021011,8075,8,7,12,26,9,92,9,11,15,...,7,4,1,5,18,32,30,53,42,47
2819098,2206,173,0,10,18,8,76,0,3,37,...,3,1,9,20,0,0,0,0,0,0
2912314,99,40,35,60,36,44,72,0,9,69,...,39,46,26,47,25,21,0,25,43,43
2785746,90,85,75,133,28,96,115,2,26,161,...,120,131,52,118,19,24,0,23,93,25
2751176,119,1173,12,5,39,0,355,0,11,231,...,0,0,14,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2032573,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1298531,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
693627,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
693629,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
Total_reads,25723079,25386963,18763016,41309990,18950755,23416543,32901040,17351886,10636072,35413053,...,24769854,35938893,16950294,29595491,15116776,17275697,15022626,14138124,12123846,15687315

In [23]:
# Normalize: divide reads by total reads and multiply by 1 million
normalized_otu = (normalized_otus / normalized_otus.loc['Total_reads'] * 1E6)
# replace total reads row again 
normalized_otu.loc['Total_reads',:]=normalized_otus.loc['Total_reads',:]
normalized_otu["Sum"]=normalized_otu.sum(axis=1)
normalized_otu.sort_values(by="Sum", ascending=False)

,052022_BEL_CBC_T1_10_PSTR,052022_BEL_CBC_T1_11_PSTR,052022_BEL_CBC_T1_4_PSTR,052022_BEL_CBC_T1_55_PSTR,052022_BEL_CBC_T2_13_PSTR,052022_BEL_CBC_T2_14_PSTR,052022_BEL_CBC_T2_45_PSTR,052022_BEL_CBC_T2_46_PSTR,052022_BEL_CBC_T2_7_PSTR,052022_BEL_CBC_T2_8_PSTR,...,102019_BEL_CBC_T3_38_PSTR,102019_BEL_CBC_T3_39_PSTR,102019_BEL_CBC_T3_40_PSTR,SRR8573788,SRR8573789,SRR8573790,SRR8573791,SRR8573793,SRR8573796,Sum
Total_reads,2.572308e+07,2.538696e+07,1.876302e+07,4.130999e+07,1.895076e+07,2.341654e+07,3.290104e+07,1.735189e+07,1.063607e+07,3.541305e+07,...,3.593889e+07,1.695029e+07,2.959549e+07,1.511678e+07,1.727570e+07,1.502263e+07,1.413812e+07,1.212385e+07,1.568732e+07,9.194410e+08
9606,7.239413e+03,6.454179e+03,6.867659e+03,6.908523e+03,1.155822e+04,8.239389e+03,7.525203e+03,3.847247e+03,8.150659e+03,7.310779e+03,...,6.810950e+03,7.072621e+03,7.857988e+03,2.584347e+03,8.516010e+03,2.008304e+03,1.985412e+03,5.244375e+03,1.188731e+04,2.690514e+05
296,2.721292e-01,3.151224e-01,2.664817e-01,4.357300e-01,1.055367e+00,6.405728e-01,7.902486e-01,5.763062e-02,5.077062e+00,7.624307e-01,...,6.399752e-01,1.179921e-01,1.351557e-01,1.772865e+01,6.589662e+03,7.163568e+04,2.232977e+04,7.680896e+03,3.091670e+01,1.083390e+05
43948,1.555024e-01,7.878059e-02,5.329634e-02,7.262166e-02,4.221468e-01,5.978679e-01,6.078835e-01,5.763062e-02,9.401967e-01,1.694291e-01,...,2.782501e-02,5.899603e-02,3.041004e-01,6.224872e+01,2.703219e+01,1.233473e+02,9.173070e+02,4.736624e+04,5.800865e+00,4.851001e+04
28901,7.943062e+02,2.642498e+03,1.095559e+03,2.272356e+03,1.103070e+03,1.102938e+03,8.429825e+02,1.440189e+02,1.819375e+03,1.102927e+03,...,5.780367e+02,2.574587e+02,1.043031e+03,3.003286e+02,2.249982e+02,1.073048e+02,1.428054e+02,1.898737e+02,2.294210e+02,3.662821e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1608100,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
1608134,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
1911435,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
1955137,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
1608112,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00

In [24]:
# export otu table to csv
normalized_otu.to_csv("otu_normtable_species.csv")